// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BrokerRank.proto

package com.bcasekuritas.rabbitmq.proto.brokerrank;

/**
 * Protobuf type {@code com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingDiscover}
 */
public final class BrokerRankingDiscover extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingDiscover)
    BrokerRankingDiscoverOrBuilder {
  // Use BrokerRankingDiscover.newBuilder() to construct.
  private BrokerRankingDiscover(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private BrokerRankingDiscover(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final BrokerRankingDiscover defaultInstance;
  public static BrokerRankingDiscover getDefaultInstance() {
    return defaultInstance;
  }

  public BrokerRankingDiscover getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private BrokerRankingDiscover(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000001;
            brokerCode_ = bs;
            break;
          }
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000002;
            brokerName_ = bs;
            break;
          }
          case 25: {
            bitField0_ |= 0x00000004;
            vol_ = input.readDouble();
            break;
          }
          case 33: {
            bitField0_ |= 0x00000008;
            val_ = input.readDouble();
            break;
          }
          case 41: {
            bitField0_ |= 0x00000010;
            freq_ = input.readDouble();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRank.internal_static_com_bcasekuritas_rabbitmq_proto_brokerrank_BrokerRankingDiscover_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRank.internal_static_com_bcasekuritas_rabbitmq_proto_brokerrank_BrokerRankingDiscover_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingDiscover.class, com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingDiscover.Builder.class);
  }

  public static com.google.protobuf.Parser<BrokerRankingDiscover> PARSER =
      new com.google.protobuf.AbstractParser<BrokerRankingDiscover>() {
    public BrokerRankingDiscover parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BrokerRankingDiscover(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<BrokerRankingDiscover> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  public static final int BROKERCODE_FIELD_NUMBER = 1;
  private java.lang.Object brokerCode_;
  /**
   * <code>optional string brokerCode = 1;</code>
   */
  public boolean hasBrokerCode() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional string brokerCode = 1;</code>
   */
  public java.lang.String getBrokerCode() {
    java.lang.Object ref = brokerCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        brokerCode_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string brokerCode = 1;</code>
   */
  public com.google.protobuf.ByteString
      getBrokerCodeBytes() {
    java.lang.Object ref = brokerCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      brokerCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BROKERNAME_FIELD_NUMBER = 2;
  private java.lang.Object brokerName_;
  /**
   * <code>optional string brokerName = 2;</code>
   */
  public boolean hasBrokerName() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional string brokerName = 2;</code>
   */
  public java.lang.String getBrokerName() {
    java.lang.Object ref = brokerName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        brokerName_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string brokerName = 2;</code>
   */
  public com.google.protobuf.ByteString
      getBrokerNameBytes() {
    java.lang.Object ref = brokerName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      brokerName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VOL_FIELD_NUMBER = 3;
  private double vol_;
  /**
   * <code>optional double vol = 3;</code>
   */
  public boolean hasVol() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional double vol = 3;</code>
   */
  public double getVol() {
    return vol_;
  }

  public static final int VAL_FIELD_NUMBER = 4;
  private double val_;
  /**
   * <code>optional double val = 4;</code>
   */
  public boolean hasVal() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>optional double val = 4;</code>
   */
  public double getVal() {
    return val_;
  }

  public static final int FREQ_FIELD_NUMBER = 5;
  private double freq_;
  /**
   * <code>optional double freq = 5;</code>
   */
  public boolean hasFreq() {
    return ((bitField0_ & 0x00000010) == 0x00000010);
  }
  /**
   * <code>optional double freq = 5;</code>
   */
  public double getFreq() {
    return freq_;
  }

  private void initFields() {
    brokerCode_ = "";
    brokerName_ = "";
    vol_ = 0D;
    val_ = 0D;
    freq_ = 0D;
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeBytes(1, getBrokerCodeBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeBytes(2, getBrokerNameBytes());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeDouble(3, vol_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeDouble(4, val_);
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      output.writeDouble(5, freq_);
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, getBrokerCodeBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, getBrokerNameBytes());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, vol_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, val_);
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(5, freq_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingDiscover parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingDiscover parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingDiscover parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingDiscover parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingDiscover parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingDiscover parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingDiscover parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingDiscover parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingDiscover parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingDiscover parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingDiscover prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingDiscover}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingDiscover)
      com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingDiscoverOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRank.internal_static_com_bcasekuritas_rabbitmq_proto_brokerrank_BrokerRankingDiscover_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRank.internal_static_com_bcasekuritas_rabbitmq_proto_brokerrank_BrokerRankingDiscover_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingDiscover.class, com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingDiscover.Builder.class);
    }

    // Construct using com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingDiscover.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      brokerCode_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      brokerName_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      vol_ = 0D;
      bitField0_ = (bitField0_ & ~0x00000004);
      val_ = 0D;
      bitField0_ = (bitField0_ & ~0x00000008);
      freq_ = 0D;
      bitField0_ = (bitField0_ & ~0x00000010);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRank.internal_static_com_bcasekuritas_rabbitmq_proto_brokerrank_BrokerRankingDiscover_descriptor;
    }

    public com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingDiscover getDefaultInstanceForType() {
      return com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingDiscover.getDefaultInstance();
    }

    public com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingDiscover build() {
      com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingDiscover result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingDiscover buildPartial() {
      com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingDiscover result = new com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingDiscover(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.brokerCode_ = brokerCode_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.brokerName_ = brokerName_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.vol_ = vol_;
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000008;
      }
      result.val_ = val_;
      if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
        to_bitField0_ |= 0x00000010;
      }
      result.freq_ = freq_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingDiscover) {
        return mergeFrom((com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingDiscover)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingDiscover other) {
      if (other == com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingDiscover.getDefaultInstance()) return this;
      if (other.hasBrokerCode()) {
        bitField0_ |= 0x00000001;
        brokerCode_ = other.brokerCode_;
        onChanged();
      }
      if (other.hasBrokerName()) {
        bitField0_ |= 0x00000002;
        brokerName_ = other.brokerName_;
        onChanged();
      }
      if (other.hasVol()) {
        setVol(other.getVol());
      }
      if (other.hasVal()) {
        setVal(other.getVal());
      }
      if (other.hasFreq()) {
        setFreq(other.getFreq());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingDiscover parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingDiscover) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object brokerCode_ = "";
    /**
     * <code>optional string brokerCode = 1;</code>
     */
    public boolean hasBrokerCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string brokerCode = 1;</code>
     */
    public java.lang.String getBrokerCode() {
      java.lang.Object ref = brokerCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          brokerCode_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string brokerCode = 1;</code>
     */
    public com.google.protobuf.ByteString
        getBrokerCodeBytes() {
      java.lang.Object ref = brokerCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        brokerCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string brokerCode = 1;</code>
     */
    public Builder setBrokerCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      brokerCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string brokerCode = 1;</code>
     */
    public Builder clearBrokerCode() {
      bitField0_ = (bitField0_ & ~0x00000001);
      brokerCode_ = getDefaultInstance().getBrokerCode();
      onChanged();
      return this;
    }
    /**
     * <code>optional string brokerCode = 1;</code>
     */
    public Builder setBrokerCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      brokerCode_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object brokerName_ = "";
    /**
     * <code>optional string brokerName = 2;</code>
     */
    public boolean hasBrokerName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string brokerName = 2;</code>
     */
    public java.lang.String getBrokerName() {
      java.lang.Object ref = brokerName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          brokerName_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string brokerName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getBrokerNameBytes() {
      java.lang.Object ref = brokerName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        brokerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string brokerName = 2;</code>
     */
    public Builder setBrokerName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      brokerName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string brokerName = 2;</code>
     */
    public Builder clearBrokerName() {
      bitField0_ = (bitField0_ & ~0x00000002);
      brokerName_ = getDefaultInstance().getBrokerName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string brokerName = 2;</code>
     */
    public Builder setBrokerNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      brokerName_ = value;
      onChanged();
      return this;
    }

    private double vol_ ;
    /**
     * <code>optional double vol = 3;</code>
     */
    public boolean hasVol() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional double vol = 3;</code>
     */
    public double getVol() {
      return vol_;
    }
    /**
     * <code>optional double vol = 3;</code>
     */
    public Builder setVol(double value) {
      bitField0_ |= 0x00000004;
      vol_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional double vol = 3;</code>
     */
    public Builder clearVol() {
      bitField0_ = (bitField0_ & ~0x00000004);
      vol_ = 0D;
      onChanged();
      return this;
    }

    private double val_ ;
    /**
     * <code>optional double val = 4;</code>
     */
    public boolean hasVal() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional double val = 4;</code>
     */
    public double getVal() {
      return val_;
    }
    /**
     * <code>optional double val = 4;</code>
     */
    public Builder setVal(double value) {
      bitField0_ |= 0x00000008;
      val_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional double val = 4;</code>
     */
    public Builder clearVal() {
      bitField0_ = (bitField0_ & ~0x00000008);
      val_ = 0D;
      onChanged();
      return this;
    }

    private double freq_ ;
    /**
     * <code>optional double freq = 5;</code>
     */
    public boolean hasFreq() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional double freq = 5;</code>
     */
    public double getFreq() {
      return freq_;
    }
    /**
     * <code>optional double freq = 5;</code>
     */
    public Builder setFreq(double value) {
      bitField0_ |= 0x00000010;
      freq_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional double freq = 5;</code>
     */
    public Builder clearFreq() {
      bitField0_ = (bitField0_ & ~0x00000010);
      freq_ = 0D;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingDiscover)
  }

  static {
    defaultInstance = new BrokerRankingDiscover(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingDiscover)
}

