// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BrokerRank.proto

package com.bcasekuritas.rabbitmq.proto.brokerrank;

/**
 * Protobuf type {@code com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingByTrxDateRequest}
 */
public final class BrokerRankingByTrxDateRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingByTrxDateRequest)
    BrokerRankingByTrxDateRequestOrBuilder {
  // Use BrokerRankingByTrxDateRequest.newBuilder() to construct.
  private BrokerRankingByTrxDateRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private BrokerRankingByTrxDateRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final BrokerRankingByTrxDateRequest defaultInstance;
  public static BrokerRankingByTrxDateRequest getDefaultInstance() {
    return defaultInstance;
  }

  public BrokerRankingByTrxDateRequest getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private BrokerRankingByTrxDateRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000001;
            userId_ = bs;
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            trxDate_ = input.readUInt64();
            break;
          }
          case 26: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000004;
            sessionId_ = bs;
            break;
          }
          case 32: {
            bitField0_ |= 0x00000008;
            sortAscending_ = input.readInt32();
            break;
          }
          case 40: {
            bitField0_ |= 0x00000010;
            sortType_ = input.readInt32();
            break;
          }
          case 48: {
            bitField0_ |= 0x00000020;
            seqNo_ = input.readInt32();
            break;
          }
          case 56: {
            bitField0_ |= 0x00000040;
            maxData_ = input.readInt32();
            break;
          }
          case 64: {
            bitField0_ |= 0x00000080;
            dataMode_ = input.readUInt32();
            break;
          }
          case 74: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000100;
            boardCode_ = bs;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRank.internal_static_com_bcasekuritas_rabbitmq_proto_brokerrank_BrokerRankingByTrxDateRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRank.internal_static_com_bcasekuritas_rabbitmq_proto_brokerrank_BrokerRankingByTrxDateRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingByTrxDateRequest.class, com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingByTrxDateRequest.Builder.class);
  }

  public static com.google.protobuf.Parser<BrokerRankingByTrxDateRequest> PARSER =
      new com.google.protobuf.AbstractParser<BrokerRankingByTrxDateRequest>() {
    public BrokerRankingByTrxDateRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BrokerRankingByTrxDateRequest(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<BrokerRankingByTrxDateRequest> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  public static final int USERID_FIELD_NUMBER = 1;
  private java.lang.Object userId_;
  /**
   * <code>required string userId = 1;</code>
   */
  public boolean hasUserId() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required string userId = 1;</code>
   */
  public java.lang.String getUserId() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        userId_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string userId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getUserIdBytes() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRXDATE_FIELD_NUMBER = 2;
  private long trxDate_;
  /**
   * <code>optional uint64 trxDate = 2;</code>
   */
  public boolean hasTrxDate() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional uint64 trxDate = 2;</code>
   */
  public long getTrxDate() {
    return trxDate_;
  }

  public static final int SESSIONID_FIELD_NUMBER = 3;
  private java.lang.Object sessionId_;
  /**
   * <code>optional string sessionId = 3;</code>
   */
  public boolean hasSessionId() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional string sessionId = 3;</code>
   */
  public java.lang.String getSessionId() {
    java.lang.Object ref = sessionId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        sessionId_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string sessionId = 3;</code>
   */
  public com.google.protobuf.ByteString
      getSessionIdBytes() {
    java.lang.Object ref = sessionId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sessionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SORTASCENDING_FIELD_NUMBER = 4;
  private int sortAscending_;
  /**
   * <code>required int32 sortAscending = 4;</code>
   *
   * <pre>
   * 0 = ascending, 1=descending
   * </pre>
   */
  public boolean hasSortAscending() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>required int32 sortAscending = 4;</code>
   *
   * <pre>
   * 0 = ascending, 1=descending
   * </pre>
   */
  public int getSortAscending() {
    return sortAscending_;
  }

  public static final int SORTTYPE_FIELD_NUMBER = 5;
  private int sortType_;
  /**
   * <code>required int32 sortType = 5;</code>
   *
   * <pre>
   * 0 = value, 1 = total volume, 2 = total freq
   * </pre>
   */
  public boolean hasSortType() {
    return ((bitField0_ & 0x00000010) == 0x00000010);
  }
  /**
   * <code>required int32 sortType = 5;</code>
   *
   * <pre>
   * 0 = value, 1 = total volume, 2 = total freq
   * </pre>
   */
  public int getSortType() {
    return sortType_;
  }

  public static final int SEQNO_FIELD_NUMBER = 6;
  private int seqNo_;
  /**
   * <code>required int32 seqNo = 6;</code>
   *
   * <pre>
   * start seq number request
   * </pre>
   */
  public boolean hasSeqNo() {
    return ((bitField0_ & 0x00000020) == 0x00000020);
  }
  /**
   * <code>required int32 seqNo = 6;</code>
   *
   * <pre>
   * start seq number request
   * </pre>
   */
  public int getSeqNo() {
    return seqNo_;
  }

  public static final int MAXDATA_FIELD_NUMBER = 7;
  private int maxData_;
  /**
   * <code>required int32 maxData = 7;</code>
   *
   * <pre>
   * max data per request -&gt; &lt;= 0 send all start seq to last data
   * </pre>
   */
  public boolean hasMaxData() {
    return ((bitField0_ & 0x00000040) == 0x00000040);
  }
  /**
   * <code>required int32 maxData = 7;</code>
   *
   * <pre>
   * max data per request -&gt; &lt;= 0 send all start seq to last data
   * </pre>
   */
  public int getMaxData() {
    return maxData_;
  }

  public static final int DATAMODE_FIELD_NUMBER = 8;
  private int dataMode_;
  /**
   * <code>optional uint32 dataMode = 8;</code>
   *
   * <pre>
   *0=compact, 1=full
   * </pre>
   */
  public boolean hasDataMode() {
    return ((bitField0_ & 0x00000080) == 0x00000080);
  }
  /**
   * <code>optional uint32 dataMode = 8;</code>
   *
   * <pre>
   *0=compact, 1=full
   * </pre>
   */
  public int getDataMode() {
    return dataMode_;
  }

  public static final int BOARDCODE_FIELD_NUMBER = 9;
  private java.lang.Object boardCode_;
  /**
   * <code>optional string boardCode = 9;</code>
   *
   * <pre>
   ** or unset for all board
   * </pre>
   */
  public boolean hasBoardCode() {
    return ((bitField0_ & 0x00000100) == 0x00000100);
  }
  /**
   * <code>optional string boardCode = 9;</code>
   *
   * <pre>
   ** or unset for all board
   * </pre>
   */
  public java.lang.String getBoardCode() {
    java.lang.Object ref = boardCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        boardCode_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string boardCode = 9;</code>
   *
   * <pre>
   ** or unset for all board
   * </pre>
   */
  public com.google.protobuf.ByteString
      getBoardCodeBytes() {
    java.lang.Object ref = boardCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      boardCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private void initFields() {
    userId_ = "";
    trxDate_ = 0L;
    sessionId_ = "";
    sortAscending_ = 0;
    sortType_ = 0;
    seqNo_ = 0;
    maxData_ = 0;
    dataMode_ = 0;
    boardCode_ = "";
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasUserId()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasSortAscending()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasSortType()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasSeqNo()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasMaxData()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeBytes(1, getUserIdBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeUInt64(2, trxDate_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeBytes(3, getSessionIdBytes());
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeInt32(4, sortAscending_);
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      output.writeInt32(5, sortType_);
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      output.writeInt32(6, seqNo_);
    }
    if (((bitField0_ & 0x00000040) == 0x00000040)) {
      output.writeInt32(7, maxData_);
    }
    if (((bitField0_ & 0x00000080) == 0x00000080)) {
      output.writeUInt32(8, dataMode_);
    }
    if (((bitField0_ & 0x00000100) == 0x00000100)) {
      output.writeBytes(9, getBoardCodeBytes());
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, getUserIdBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(2, trxDate_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, getSessionIdBytes());
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, sortAscending_);
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, sortType_);
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, seqNo_);
    }
    if (((bitField0_ & 0x00000040) == 0x00000040)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, maxData_);
    }
    if (((bitField0_ & 0x00000080) == 0x00000080)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(8, dataMode_);
    }
    if (((bitField0_ & 0x00000100) == 0x00000100)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(9, getBoardCodeBytes());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingByTrxDateRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingByTrxDateRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingByTrxDateRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingByTrxDateRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingByTrxDateRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingByTrxDateRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingByTrxDateRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingByTrxDateRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingByTrxDateRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingByTrxDateRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingByTrxDateRequest prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingByTrxDateRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingByTrxDateRequest)
      com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingByTrxDateRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRank.internal_static_com_bcasekuritas_rabbitmq_proto_brokerrank_BrokerRankingByTrxDateRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRank.internal_static_com_bcasekuritas_rabbitmq_proto_brokerrank_BrokerRankingByTrxDateRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingByTrxDateRequest.class, com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingByTrxDateRequest.Builder.class);
    }

    // Construct using com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingByTrxDateRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      userId_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      trxDate_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000002);
      sessionId_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      sortAscending_ = 0;
      bitField0_ = (bitField0_ & ~0x00000008);
      sortType_ = 0;
      bitField0_ = (bitField0_ & ~0x00000010);
      seqNo_ = 0;
      bitField0_ = (bitField0_ & ~0x00000020);
      maxData_ = 0;
      bitField0_ = (bitField0_ & ~0x00000040);
      dataMode_ = 0;
      bitField0_ = (bitField0_ & ~0x00000080);
      boardCode_ = "";
      bitField0_ = (bitField0_ & ~0x00000100);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRank.internal_static_com_bcasekuritas_rabbitmq_proto_brokerrank_BrokerRankingByTrxDateRequest_descriptor;
    }

    public com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingByTrxDateRequest getDefaultInstanceForType() {
      return com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingByTrxDateRequest.getDefaultInstance();
    }

    public com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingByTrxDateRequest build() {
      com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingByTrxDateRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingByTrxDateRequest buildPartial() {
      com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingByTrxDateRequest result = new com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingByTrxDateRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.userId_ = userId_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.trxDate_ = trxDate_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.sessionId_ = sessionId_;
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000008;
      }
      result.sortAscending_ = sortAscending_;
      if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
        to_bitField0_ |= 0x00000010;
      }
      result.sortType_ = sortType_;
      if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
        to_bitField0_ |= 0x00000020;
      }
      result.seqNo_ = seqNo_;
      if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
        to_bitField0_ |= 0x00000040;
      }
      result.maxData_ = maxData_;
      if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
        to_bitField0_ |= 0x00000080;
      }
      result.dataMode_ = dataMode_;
      if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
        to_bitField0_ |= 0x00000100;
      }
      result.boardCode_ = boardCode_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingByTrxDateRequest) {
        return mergeFrom((com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingByTrxDateRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingByTrxDateRequest other) {
      if (other == com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingByTrxDateRequest.getDefaultInstance()) return this;
      if (other.hasUserId()) {
        bitField0_ |= 0x00000001;
        userId_ = other.userId_;
        onChanged();
      }
      if (other.hasTrxDate()) {
        setTrxDate(other.getTrxDate());
      }
      if (other.hasSessionId()) {
        bitField0_ |= 0x00000004;
        sessionId_ = other.sessionId_;
        onChanged();
      }
      if (other.hasSortAscending()) {
        setSortAscending(other.getSortAscending());
      }
      if (other.hasSortType()) {
        setSortType(other.getSortType());
      }
      if (other.hasSeqNo()) {
        setSeqNo(other.getSeqNo());
      }
      if (other.hasMaxData()) {
        setMaxData(other.getMaxData());
      }
      if (other.hasDataMode()) {
        setDataMode(other.getDataMode());
      }
      if (other.hasBoardCode()) {
        bitField0_ |= 0x00000100;
        boardCode_ = other.boardCode_;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasUserId()) {
        
        return false;
      }
      if (!hasSortAscending()) {
        
        return false;
      }
      if (!hasSortType()) {
        
        return false;
      }
      if (!hasSeqNo()) {
        
        return false;
      }
      if (!hasMaxData()) {
        
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingByTrxDateRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingByTrxDateRequest) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object userId_ = "";
    /**
     * <code>required string userId = 1;</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string userId = 1;</code>
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userId_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string userId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string userId = 1;</code>
     */
    public Builder setUserId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      userId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string userId = 1;</code>
     */
    public Builder clearUserId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      userId_ = getDefaultInstance().getUserId();
      onChanged();
      return this;
    }
    /**
     * <code>required string userId = 1;</code>
     */
    public Builder setUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      userId_ = value;
      onChanged();
      return this;
    }

    private long trxDate_ ;
    /**
     * <code>optional uint64 trxDate = 2;</code>
     */
    public boolean hasTrxDate() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint64 trxDate = 2;</code>
     */
    public long getTrxDate() {
      return trxDate_;
    }
    /**
     * <code>optional uint64 trxDate = 2;</code>
     */
    public Builder setTrxDate(long value) {
      bitField0_ |= 0x00000002;
      trxDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint64 trxDate = 2;</code>
     */
    public Builder clearTrxDate() {
      bitField0_ = (bitField0_ & ~0x00000002);
      trxDate_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object sessionId_ = "";
    /**
     * <code>optional string sessionId = 3;</code>
     */
    public boolean hasSessionId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string sessionId = 3;</code>
     */
    public java.lang.String getSessionId() {
      java.lang.Object ref = sessionId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sessionId_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string sessionId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSessionIdBytes() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string sessionId = 3;</code>
     */
    public Builder setSessionId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      sessionId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string sessionId = 3;</code>
     */
    public Builder clearSessionId() {
      bitField0_ = (bitField0_ & ~0x00000004);
      sessionId_ = getDefaultInstance().getSessionId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string sessionId = 3;</code>
     */
    public Builder setSessionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      sessionId_ = value;
      onChanged();
      return this;
    }

    private int sortAscending_ ;
    /**
     * <code>required int32 sortAscending = 4;</code>
     *
     * <pre>
     * 0 = ascending, 1=descending
     * </pre>
     */
    public boolean hasSortAscending() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 sortAscending = 4;</code>
     *
     * <pre>
     * 0 = ascending, 1=descending
     * </pre>
     */
    public int getSortAscending() {
      return sortAscending_;
    }
    /**
     * <code>required int32 sortAscending = 4;</code>
     *
     * <pre>
     * 0 = ascending, 1=descending
     * </pre>
     */
    public Builder setSortAscending(int value) {
      bitField0_ |= 0x00000008;
      sortAscending_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 sortAscending = 4;</code>
     *
     * <pre>
     * 0 = ascending, 1=descending
     * </pre>
     */
    public Builder clearSortAscending() {
      bitField0_ = (bitField0_ & ~0x00000008);
      sortAscending_ = 0;
      onChanged();
      return this;
    }

    private int sortType_ ;
    /**
     * <code>required int32 sortType = 5;</code>
     *
     * <pre>
     * 0 = value, 1 = total volume, 2 = total freq
     * </pre>
     */
    public boolean hasSortType() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 sortType = 5;</code>
     *
     * <pre>
     * 0 = value, 1 = total volume, 2 = total freq
     * </pre>
     */
    public int getSortType() {
      return sortType_;
    }
    /**
     * <code>required int32 sortType = 5;</code>
     *
     * <pre>
     * 0 = value, 1 = total volume, 2 = total freq
     * </pre>
     */
    public Builder setSortType(int value) {
      bitField0_ |= 0x00000010;
      sortType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 sortType = 5;</code>
     *
     * <pre>
     * 0 = value, 1 = total volume, 2 = total freq
     * </pre>
     */
    public Builder clearSortType() {
      bitField0_ = (bitField0_ & ~0x00000010);
      sortType_ = 0;
      onChanged();
      return this;
    }

    private int seqNo_ ;
    /**
     * <code>required int32 seqNo = 6;</code>
     *
     * <pre>
     * start seq number request
     * </pre>
     */
    public boolean hasSeqNo() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required int32 seqNo = 6;</code>
     *
     * <pre>
     * start seq number request
     * </pre>
     */
    public int getSeqNo() {
      return seqNo_;
    }
    /**
     * <code>required int32 seqNo = 6;</code>
     *
     * <pre>
     * start seq number request
     * </pre>
     */
    public Builder setSeqNo(int value) {
      bitField0_ |= 0x00000020;
      seqNo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 seqNo = 6;</code>
     *
     * <pre>
     * start seq number request
     * </pre>
     */
    public Builder clearSeqNo() {
      bitField0_ = (bitField0_ & ~0x00000020);
      seqNo_ = 0;
      onChanged();
      return this;
    }

    private int maxData_ ;
    /**
     * <code>required int32 maxData = 7;</code>
     *
     * <pre>
     * max data per request -&gt; &lt;= 0 send all start seq to last data
     * </pre>
     */
    public boolean hasMaxData() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required int32 maxData = 7;</code>
     *
     * <pre>
     * max data per request -&gt; &lt;= 0 send all start seq to last data
     * </pre>
     */
    public int getMaxData() {
      return maxData_;
    }
    /**
     * <code>required int32 maxData = 7;</code>
     *
     * <pre>
     * max data per request -&gt; &lt;= 0 send all start seq to last data
     * </pre>
     */
    public Builder setMaxData(int value) {
      bitField0_ |= 0x00000040;
      maxData_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 maxData = 7;</code>
     *
     * <pre>
     * max data per request -&gt; &lt;= 0 send all start seq to last data
     * </pre>
     */
    public Builder clearMaxData() {
      bitField0_ = (bitField0_ & ~0x00000040);
      maxData_ = 0;
      onChanged();
      return this;
    }

    private int dataMode_ ;
    /**
     * <code>optional uint32 dataMode = 8;</code>
     *
     * <pre>
     *0=compact, 1=full
     * </pre>
     */
    public boolean hasDataMode() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional uint32 dataMode = 8;</code>
     *
     * <pre>
     *0=compact, 1=full
     * </pre>
     */
    public int getDataMode() {
      return dataMode_;
    }
    /**
     * <code>optional uint32 dataMode = 8;</code>
     *
     * <pre>
     *0=compact, 1=full
     * </pre>
     */
    public Builder setDataMode(int value) {
      bitField0_ |= 0x00000080;
      dataMode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint32 dataMode = 8;</code>
     *
     * <pre>
     *0=compact, 1=full
     * </pre>
     */
    public Builder clearDataMode() {
      bitField0_ = (bitField0_ & ~0x00000080);
      dataMode_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object boardCode_ = "";
    /**
     * <code>optional string boardCode = 9;</code>
     *
     * <pre>
     ** or unset for all board
     * </pre>
     */
    public boolean hasBoardCode() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional string boardCode = 9;</code>
     *
     * <pre>
     ** or unset for all board
     * </pre>
     */
    public java.lang.String getBoardCode() {
      java.lang.Object ref = boardCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          boardCode_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string boardCode = 9;</code>
     *
     * <pre>
     ** or unset for all board
     * </pre>
     */
    public com.google.protobuf.ByteString
        getBoardCodeBytes() {
      java.lang.Object ref = boardCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        boardCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string boardCode = 9;</code>
     *
     * <pre>
     ** or unset for all board
     * </pre>
     */
    public Builder setBoardCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
      boardCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string boardCode = 9;</code>
     *
     * <pre>
     ** or unset for all board
     * </pre>
     */
    public Builder clearBoardCode() {
      bitField0_ = (bitField0_ & ~0x00000100);
      boardCode_ = getDefaultInstance().getBoardCode();
      onChanged();
      return this;
    }
    /**
     * <code>optional string boardCode = 9;</code>
     *
     * <pre>
     ** or unset for all board
     * </pre>
     */
    public Builder setBoardCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
      boardCode_ = value;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingByTrxDateRequest)
  }

  static {
    defaultInstance = new BrokerRankingByTrxDateRequest(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRankingByTrxDateRequest)
}

