// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BrokerRank.proto

package com.bcasekuritas.rabbitmq.proto.brokerrank;

/**
 * Protobuf type {@code com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerListRequest}
 */
public final class BrokerListRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerListRequest)
    BrokerListRequestOrBuilder {
  // Use BrokerListRequest.newBuilder() to construct.
  private BrokerListRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private BrokerListRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final BrokerListRequest defaultInstance;
  public static BrokerListRequest getDefaultInstance() {
    return defaultInstance;
  }

  public BrokerListRequest getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private BrokerListRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000001;
            userId_ = bs;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRank.internal_static_com_bcasekuritas_rabbitmq_proto_brokerrank_BrokerListRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRank.internal_static_com_bcasekuritas_rabbitmq_proto_brokerrank_BrokerListRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerListRequest.class, com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerListRequest.Builder.class);
  }

  public static com.google.protobuf.Parser<BrokerListRequest> PARSER =
      new com.google.protobuf.AbstractParser<BrokerListRequest>() {
    public BrokerListRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BrokerListRequest(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<BrokerListRequest> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  public static final int USERID_FIELD_NUMBER = 1;
  private java.lang.Object userId_;
  /**
   * <code>required string userId = 1;</code>
   */
  public boolean hasUserId() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required string userId = 1;</code>
   */
  public java.lang.String getUserId() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        userId_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string userId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getUserIdBytes() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private void initFields() {
    userId_ = "";
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasUserId()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeBytes(1, getUserIdBytes());
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, getUserIdBytes());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerListRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerListRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerListRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerListRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerListRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerListRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerListRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerListRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerListRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerListRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerListRequest prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerListRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerListRequest)
      com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerListRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRank.internal_static_com_bcasekuritas_rabbitmq_proto_brokerrank_BrokerListRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRank.internal_static_com_bcasekuritas_rabbitmq_proto_brokerrank_BrokerListRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerListRequest.class, com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerListRequest.Builder.class);
    }

    // Construct using com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerListRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      userId_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerRank.internal_static_com_bcasekuritas_rabbitmq_proto_brokerrank_BrokerListRequest_descriptor;
    }

    public com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerListRequest getDefaultInstanceForType() {
      return com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerListRequest.getDefaultInstance();
    }

    public com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerListRequest build() {
      com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerListRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerListRequest buildPartial() {
      com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerListRequest result = new com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerListRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.userId_ = userId_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerListRequest) {
        return mergeFrom((com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerListRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerListRequest other) {
      if (other == com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerListRequest.getDefaultInstance()) return this;
      if (other.hasUserId()) {
        bitField0_ |= 0x00000001;
        userId_ = other.userId_;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasUserId()) {
        
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerListRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerListRequest) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object userId_ = "";
    /**
     * <code>required string userId = 1;</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string userId = 1;</code>
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userId_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string userId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string userId = 1;</code>
     */
    public Builder setUserId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      userId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string userId = 1;</code>
     */
    public Builder clearUserId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      userId_ = getDefaultInstance().getUserId();
      onChanged();
      return this;
    }
    /**
     * <code>required string userId = 1;</code>
     */
    public Builder setUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      userId_ = value;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerListRequest)
  }

  static {
    defaultInstance = new BrokerListRequest(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:com.bcasekuritas.rabbitmq.proto.brokerrank.BrokerListRequest)
}

