package com.bcasekuritas.mybest.ext.constant

object Args {

    // PARAM ACTIVITY
    const val EXTRA_PARAM_STR_ONE = "PARAM_STR_ONE_OPEN_LAYOUT"
    const val EXTRA_PARAM_STR_TWO = "PARAM_STR_TWO_OPEN_LAYOUT"
    const val EXTRA_PARAM_INT_ONE = "PARAM_INT_ONE_OPEN_LAYOUT"
    const val EXTRA_PARAM_INT_TWO = "PARAM_INT_TWO_OPEN_LAYOUT"
    const val EXTRA_PARAM_DOUBLE_ONE = "PARAM_DOUBLE_ONE_OPEN_LAYOUT"
    const val EXTRA_PARAM_OBJECT = "PARAM_OBJECT_OPEN_LAYOUT"
    const val EXTRA_PARAM_OBJECT_TWO = "PARAM_OBJECT_OPEN_TWO"
    const val EXTRA_PARAM_BOOLEAN = "PARAM_BOOLEAN_OPEN_LAYOUT"
    const val EXTRA_PARAM_BOOLEAN_TWO = "PARAM_BOOLEAN_TWO_OPEN_LAYOUT"

    // AUTH
    const val EXTRA_AUTHENTICATION = "EXTRA_AUTH"
    const val EXTRA_NOTIFICATION_ID = "NOTIFICATION_ID"
    const val EXTRA_VALUE_CREDENTIAL_FORBIDDEN = "CREDENTIAL_FORBIDDEN"

    // DIALOG
    const val EXTRA_UI_DIALOG_MODEL = "UI_DIALOG_MODEL"

    // BROADCAST
    const val EXTRA_BROADCAST_CON = "BROADCAST_CON"

}