// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: News.proto

package com.bcasekuritas.rabbitmq.proto.news;

/**
 * Protobuf type {@code com.bcasekuritas.rabbitmq.proto.news.AssetsRequest}
 */
public final class AssetsRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.bcasekuritas.rabbitmq.proto.news.AssetsRequest)
    AssetsRequestOrBuilder {
  // Use AssetsRequest.newBuilder() to construct.
  private AssetsRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private AssetsRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final AssetsRequest defaultInstance;
  public static AssetsRequest getDefaultInstance() {
    return defaultInstance;
  }

  public AssetsRequest getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private AssetsRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000001;
            userId_ = bs;
            break;
          }
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000002;
            sessionId_ = bs;
            break;
          }
          case 24: {
            bitField0_ |= 0x00000004;
            page_ = input.readUInt32();
            break;
          }
          case 32: {
            bitField0_ |= 0x00000008;
            size_ = input.readUInt32();
            break;
          }
          case 40: {
            bitField0_ |= 0x00000010;
            requestType_ = input.readUInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bcasekuritas.rabbitmq.proto.news.News.internal_static_com_bcasekuritas_rabbitmq_proto_news_AssetsRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bcasekuritas.rabbitmq.proto.news.News.internal_static_com_bcasekuritas_rabbitmq_proto_news_AssetsRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bcasekuritas.rabbitmq.proto.news.AssetsRequest.class, com.bcasekuritas.rabbitmq.proto.news.AssetsRequest.Builder.class);
  }

  public static com.google.protobuf.Parser<AssetsRequest> PARSER =
      new com.google.protobuf.AbstractParser<AssetsRequest>() {
    public AssetsRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AssetsRequest(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<AssetsRequest> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  public static final int USERID_FIELD_NUMBER = 1;
  private java.lang.Object userId_;
  /**
   * <code>required string userId = 1;</code>
   */
  public boolean hasUserId() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required string userId = 1;</code>
   */
  public java.lang.String getUserId() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        userId_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string userId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getUserIdBytes() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SESSIONID_FIELD_NUMBER = 2;
  private java.lang.Object sessionId_;
  /**
   * <code>optional string sessionId = 2;</code>
   */
  public boolean hasSessionId() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional string sessionId = 2;</code>
   */
  public java.lang.String getSessionId() {
    java.lang.Object ref = sessionId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        sessionId_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string sessionId = 2;</code>
   */
  public com.google.protobuf.ByteString
      getSessionIdBytes() {
    java.lang.Object ref = sessionId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sessionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PAGE_FIELD_NUMBER = 3;
  private int page_;
  /**
   * <code>required uint32 page = 3;</code>
   */
  public boolean hasPage() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>required uint32 page = 3;</code>
   */
  public int getPage() {
    return page_;
  }

  public static final int SIZE_FIELD_NUMBER = 4;
  private int size_;
  /**
   * <code>required uint32 size = 4;</code>
   */
  public boolean hasSize() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>required uint32 size = 4;</code>
   */
  public int getSize() {
    return size_;
  }

  public static final int REQUESTTYPE_FIELD_NUMBER = 5;
  private int requestType_;
  /**
   * <code>required uint32 requestType = 5;</code>
   *
   * <pre>
   * 1 = icon, 2 = logo, 3 = all whithout filter by type
   * </pre>
   */
  public boolean hasRequestType() {
    return ((bitField0_ & 0x00000010) == 0x00000010);
  }
  /**
   * <code>required uint32 requestType = 5;</code>
   *
   * <pre>
   * 1 = icon, 2 = logo, 3 = all whithout filter by type
   * </pre>
   */
  public int getRequestType() {
    return requestType_;
  }

  private void initFields() {
    userId_ = "";
    sessionId_ = "";
    page_ = 0;
    size_ = 0;
    requestType_ = 0;
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasUserId()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasPage()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasSize()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasRequestType()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeBytes(1, getUserIdBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeBytes(2, getSessionIdBytes());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeUInt32(3, page_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeUInt32(4, size_);
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      output.writeUInt32(5, requestType_);
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, getUserIdBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, getSessionIdBytes());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, page_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(4, size_);
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(5, requestType_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static com.bcasekuritas.rabbitmq.proto.news.AssetsRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bcasekuritas.rabbitmq.proto.news.AssetsRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bcasekuritas.rabbitmq.proto.news.AssetsRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bcasekuritas.rabbitmq.proto.news.AssetsRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bcasekuritas.rabbitmq.proto.news.AssetsRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.bcasekuritas.rabbitmq.proto.news.AssetsRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.bcasekuritas.rabbitmq.proto.news.AssetsRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.bcasekuritas.rabbitmq.proto.news.AssetsRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.bcasekuritas.rabbitmq.proto.news.AssetsRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.bcasekuritas.rabbitmq.proto.news.AssetsRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.bcasekuritas.rabbitmq.proto.news.AssetsRequest prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.bcasekuritas.rabbitmq.proto.news.AssetsRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.bcasekuritas.rabbitmq.proto.news.AssetsRequest)
      com.bcasekuritas.rabbitmq.proto.news.AssetsRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bcasekuritas.rabbitmq.proto.news.News.internal_static_com_bcasekuritas_rabbitmq_proto_news_AssetsRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bcasekuritas.rabbitmq.proto.news.News.internal_static_com_bcasekuritas_rabbitmq_proto_news_AssetsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bcasekuritas.rabbitmq.proto.news.AssetsRequest.class, com.bcasekuritas.rabbitmq.proto.news.AssetsRequest.Builder.class);
    }

    // Construct using com.bcasekuritas.rabbitmq.proto.news.AssetsRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      userId_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      sessionId_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      page_ = 0;
      bitField0_ = (bitField0_ & ~0x00000004);
      size_ = 0;
      bitField0_ = (bitField0_ & ~0x00000008);
      requestType_ = 0;
      bitField0_ = (bitField0_ & ~0x00000010);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bcasekuritas.rabbitmq.proto.news.News.internal_static_com_bcasekuritas_rabbitmq_proto_news_AssetsRequest_descriptor;
    }

    public com.bcasekuritas.rabbitmq.proto.news.AssetsRequest getDefaultInstanceForType() {
      return com.bcasekuritas.rabbitmq.proto.news.AssetsRequest.getDefaultInstance();
    }

    public com.bcasekuritas.rabbitmq.proto.news.AssetsRequest build() {
      com.bcasekuritas.rabbitmq.proto.news.AssetsRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.bcasekuritas.rabbitmq.proto.news.AssetsRequest buildPartial() {
      com.bcasekuritas.rabbitmq.proto.news.AssetsRequest result = new com.bcasekuritas.rabbitmq.proto.news.AssetsRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.userId_ = userId_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.sessionId_ = sessionId_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.page_ = page_;
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000008;
      }
      result.size_ = size_;
      if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
        to_bitField0_ |= 0x00000010;
      }
      result.requestType_ = requestType_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bcasekuritas.rabbitmq.proto.news.AssetsRequest) {
        return mergeFrom((com.bcasekuritas.rabbitmq.proto.news.AssetsRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bcasekuritas.rabbitmq.proto.news.AssetsRequest other) {
      if (other == com.bcasekuritas.rabbitmq.proto.news.AssetsRequest.getDefaultInstance()) return this;
      if (other.hasUserId()) {
        bitField0_ |= 0x00000001;
        userId_ = other.userId_;
        onChanged();
      }
      if (other.hasSessionId()) {
        bitField0_ |= 0x00000002;
        sessionId_ = other.sessionId_;
        onChanged();
      }
      if (other.hasPage()) {
        setPage(other.getPage());
      }
      if (other.hasSize()) {
        setSize(other.getSize());
      }
      if (other.hasRequestType()) {
        setRequestType(other.getRequestType());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasUserId()) {
        
        return false;
      }
      if (!hasPage()) {
        
        return false;
      }
      if (!hasSize()) {
        
        return false;
      }
      if (!hasRequestType()) {
        
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.bcasekuritas.rabbitmq.proto.news.AssetsRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.bcasekuritas.rabbitmq.proto.news.AssetsRequest) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object userId_ = "";
    /**
     * <code>required string userId = 1;</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string userId = 1;</code>
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userId_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string userId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string userId = 1;</code>
     */
    public Builder setUserId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      userId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string userId = 1;</code>
     */
    public Builder clearUserId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      userId_ = getDefaultInstance().getUserId();
      onChanged();
      return this;
    }
    /**
     * <code>required string userId = 1;</code>
     */
    public Builder setUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      userId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object sessionId_ = "";
    /**
     * <code>optional string sessionId = 2;</code>
     */
    public boolean hasSessionId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string sessionId = 2;</code>
     */
    public java.lang.String getSessionId() {
      java.lang.Object ref = sessionId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sessionId_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string sessionId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSessionIdBytes() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string sessionId = 2;</code>
     */
    public Builder setSessionId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      sessionId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string sessionId = 2;</code>
     */
    public Builder clearSessionId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      sessionId_ = getDefaultInstance().getSessionId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string sessionId = 2;</code>
     */
    public Builder setSessionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      sessionId_ = value;
      onChanged();
      return this;
    }

    private int page_ ;
    /**
     * <code>required uint32 page = 3;</code>
     */
    public boolean hasPage() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required uint32 page = 3;</code>
     */
    public int getPage() {
      return page_;
    }
    /**
     * <code>required uint32 page = 3;</code>
     */
    public Builder setPage(int value) {
      bitField0_ |= 0x00000004;
      page_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required uint32 page = 3;</code>
     */
    public Builder clearPage() {
      bitField0_ = (bitField0_ & ~0x00000004);
      page_ = 0;
      onChanged();
      return this;
    }

    private int size_ ;
    /**
     * <code>required uint32 size = 4;</code>
     */
    public boolean hasSize() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required uint32 size = 4;</code>
     */
    public int getSize() {
      return size_;
    }
    /**
     * <code>required uint32 size = 4;</code>
     */
    public Builder setSize(int value) {
      bitField0_ |= 0x00000008;
      size_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required uint32 size = 4;</code>
     */
    public Builder clearSize() {
      bitField0_ = (bitField0_ & ~0x00000008);
      size_ = 0;
      onChanged();
      return this;
    }

    private int requestType_ ;
    /**
     * <code>required uint32 requestType = 5;</code>
     *
     * <pre>
     * 1 = icon, 2 = logo, 3 = all whithout filter by type
     * </pre>
     */
    public boolean hasRequestType() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required uint32 requestType = 5;</code>
     *
     * <pre>
     * 1 = icon, 2 = logo, 3 = all whithout filter by type
     * </pre>
     */
    public int getRequestType() {
      return requestType_;
    }
    /**
     * <code>required uint32 requestType = 5;</code>
     *
     * <pre>
     * 1 = icon, 2 = logo, 3 = all whithout filter by type
     * </pre>
     */
    public Builder setRequestType(int value) {
      bitField0_ |= 0x00000010;
      requestType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required uint32 requestType = 5;</code>
     *
     * <pre>
     * 1 = icon, 2 = logo, 3 = all whithout filter by type
     * </pre>
     */
    public Builder clearRequestType() {
      bitField0_ = (bitField0_ & ~0x00000010);
      requestType_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.bcasekuritas.rabbitmq.proto.news.AssetsRequest)
  }

  static {
    defaultInstance = new AssetsRequest(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:com.bcasekuritas.rabbitmq.proto.news.AssetsRequest)
}

