// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: News.proto

package com.bcasekuritas.rabbitmq.proto.news;

/**
 * Protobuf type {@code com.bcasekuritas.rabbitmq.proto.news.CaRightResponse}
 */
public final class CaRightResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.bcasekuritas.rabbitmq.proto.news.CaRightResponse)
    CaRightResponseOrBuilder {
  // Use CaRightResponse.newBuilder() to construct.
  private CaRightResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private CaRightResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final CaRightResponse defaultInstance;
  public static CaRightResponse getDefaultInstance() {
    return defaultInstance;
  }

  public CaRightResponse getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private CaRightResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000001;
            status_ = bs;
            break;
          }
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000002;
            remarks_ = bs;
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              caRightData_ = new java.util.ArrayList<com.bcasekuritas.rabbitmq.proto.news.CaRight>();
              mutable_bitField0_ |= 0x00000004;
            }
            caRightData_.add(input.readMessage(com.bcasekuritas.rabbitmq.proto.news.CaRight.PARSER, extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        caRightData_ = java.util.Collections.unmodifiableList(caRightData_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bcasekuritas.rabbitmq.proto.news.News.internal_static_com_bcasekuritas_rabbitmq_proto_news_CaRightResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bcasekuritas.rabbitmq.proto.news.News.internal_static_com_bcasekuritas_rabbitmq_proto_news_CaRightResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bcasekuritas.rabbitmq.proto.news.CaRightResponse.class, com.bcasekuritas.rabbitmq.proto.news.CaRightResponse.Builder.class);
  }

  public static com.google.protobuf.Parser<CaRightResponse> PARSER =
      new com.google.protobuf.AbstractParser<CaRightResponse>() {
    public CaRightResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CaRightResponse(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<CaRightResponse> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  public static final int STATUS_FIELD_NUMBER = 1;
  private java.lang.Object status_;
  /**
   * <code>optional string status = 1;</code>
   */
  public boolean hasStatus() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional string status = 1;</code>
   */
  public java.lang.String getStatus() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        status_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string status = 1;</code>
   */
  public com.google.protobuf.ByteString
      getStatusBytes() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      status_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REMARKS_FIELD_NUMBER = 2;
  private java.lang.Object remarks_;
  /**
   * <code>optional string remarks = 2;</code>
   */
  public boolean hasRemarks() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional string remarks = 2;</code>
   */
  public java.lang.String getRemarks() {
    java.lang.Object ref = remarks_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        remarks_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string remarks = 2;</code>
   */
  public com.google.protobuf.ByteString
      getRemarksBytes() {
    java.lang.Object ref = remarks_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      remarks_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CARIGHTDATA_FIELD_NUMBER = 3;
  private java.util.List<com.bcasekuritas.rabbitmq.proto.news.CaRight> caRightData_;
  /**
   * <code>repeated .com.bcasekuritas.rabbitmq.proto.news.CaRight caRightData = 3;</code>
   */
  public java.util.List<com.bcasekuritas.rabbitmq.proto.news.CaRight> getCaRightDataList() {
    return caRightData_;
  }
  /**
   * <code>repeated .com.bcasekuritas.rabbitmq.proto.news.CaRight caRightData = 3;</code>
   */
  public java.util.List<? extends com.bcasekuritas.rabbitmq.proto.news.CaRightOrBuilder> 
      getCaRightDataOrBuilderList() {
    return caRightData_;
  }
  /**
   * <code>repeated .com.bcasekuritas.rabbitmq.proto.news.CaRight caRightData = 3;</code>
   */
  public int getCaRightDataCount() {
    return caRightData_.size();
  }
  /**
   * <code>repeated .com.bcasekuritas.rabbitmq.proto.news.CaRight caRightData = 3;</code>
   */
  public com.bcasekuritas.rabbitmq.proto.news.CaRight getCaRightData(int index) {
    return caRightData_.get(index);
  }
  /**
   * <code>repeated .com.bcasekuritas.rabbitmq.proto.news.CaRight caRightData = 3;</code>
   */
  public com.bcasekuritas.rabbitmq.proto.news.CaRightOrBuilder getCaRightDataOrBuilder(
      int index) {
    return caRightData_.get(index);
  }

  private void initFields() {
    status_ = "";
    remarks_ = "";
    caRightData_ = java.util.Collections.emptyList();
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeBytes(1, getStatusBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeBytes(2, getRemarksBytes());
    }
    for (int i = 0; i < caRightData_.size(); i++) {
      output.writeMessage(3, caRightData_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, getStatusBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, getRemarksBytes());
    }
    for (int i = 0; i < caRightData_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, caRightData_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static com.bcasekuritas.rabbitmq.proto.news.CaRightResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bcasekuritas.rabbitmq.proto.news.CaRightResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bcasekuritas.rabbitmq.proto.news.CaRightResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bcasekuritas.rabbitmq.proto.news.CaRightResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bcasekuritas.rabbitmq.proto.news.CaRightResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.bcasekuritas.rabbitmq.proto.news.CaRightResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.bcasekuritas.rabbitmq.proto.news.CaRightResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.bcasekuritas.rabbitmq.proto.news.CaRightResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.bcasekuritas.rabbitmq.proto.news.CaRightResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.bcasekuritas.rabbitmq.proto.news.CaRightResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.bcasekuritas.rabbitmq.proto.news.CaRightResponse prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.bcasekuritas.rabbitmq.proto.news.CaRightResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.bcasekuritas.rabbitmq.proto.news.CaRightResponse)
      com.bcasekuritas.rabbitmq.proto.news.CaRightResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bcasekuritas.rabbitmq.proto.news.News.internal_static_com_bcasekuritas_rabbitmq_proto_news_CaRightResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bcasekuritas.rabbitmq.proto.news.News.internal_static_com_bcasekuritas_rabbitmq_proto_news_CaRightResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bcasekuritas.rabbitmq.proto.news.CaRightResponse.class, com.bcasekuritas.rabbitmq.proto.news.CaRightResponse.Builder.class);
    }

    // Construct using com.bcasekuritas.rabbitmq.proto.news.CaRightResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getCaRightDataFieldBuilder();
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      status_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      remarks_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      if (caRightDataBuilder_ == null) {
        caRightData_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        caRightDataBuilder_.clear();
      }
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bcasekuritas.rabbitmq.proto.news.News.internal_static_com_bcasekuritas_rabbitmq_proto_news_CaRightResponse_descriptor;
    }

    public com.bcasekuritas.rabbitmq.proto.news.CaRightResponse getDefaultInstanceForType() {
      return com.bcasekuritas.rabbitmq.proto.news.CaRightResponse.getDefaultInstance();
    }

    public com.bcasekuritas.rabbitmq.proto.news.CaRightResponse build() {
      com.bcasekuritas.rabbitmq.proto.news.CaRightResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.bcasekuritas.rabbitmq.proto.news.CaRightResponse buildPartial() {
      com.bcasekuritas.rabbitmq.proto.news.CaRightResponse result = new com.bcasekuritas.rabbitmq.proto.news.CaRightResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.status_ = status_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.remarks_ = remarks_;
      if (caRightDataBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          caRightData_ = java.util.Collections.unmodifiableList(caRightData_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.caRightData_ = caRightData_;
      } else {
        result.caRightData_ = caRightDataBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bcasekuritas.rabbitmq.proto.news.CaRightResponse) {
        return mergeFrom((com.bcasekuritas.rabbitmq.proto.news.CaRightResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bcasekuritas.rabbitmq.proto.news.CaRightResponse other) {
      if (other == com.bcasekuritas.rabbitmq.proto.news.CaRightResponse.getDefaultInstance()) return this;
      if (other.hasStatus()) {
        bitField0_ |= 0x00000001;
        status_ = other.status_;
        onChanged();
      }
      if (other.hasRemarks()) {
        bitField0_ |= 0x00000002;
        remarks_ = other.remarks_;
        onChanged();
      }
      if (caRightDataBuilder_ == null) {
        if (!other.caRightData_.isEmpty()) {
          if (caRightData_.isEmpty()) {
            caRightData_ = other.caRightData_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureCaRightDataIsMutable();
            caRightData_.addAll(other.caRightData_);
          }
          onChanged();
        }
      } else {
        if (!other.caRightData_.isEmpty()) {
          if (caRightDataBuilder_.isEmpty()) {
            caRightDataBuilder_.dispose();
            caRightDataBuilder_ = null;
            caRightData_ = other.caRightData_;
            bitField0_ = (bitField0_ & ~0x00000004);
            caRightDataBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getCaRightDataFieldBuilder() : null;
          } else {
            caRightDataBuilder_.addAllMessages(other.caRightData_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.bcasekuritas.rabbitmq.proto.news.CaRightResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.bcasekuritas.rabbitmq.proto.news.CaRightResponse) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object status_ = "";
    /**
     * <code>optional string status = 1;</code>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string status = 1;</code>
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          status_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string status = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string status = 1;</code>
     */
    public Builder setStatus(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string status = 1;</code>
     */
    public Builder clearStatus() {
      bitField0_ = (bitField0_ & ~0x00000001);
      status_ = getDefaultInstance().getStatus();
      onChanged();
      return this;
    }
    /**
     * <code>optional string status = 1;</code>
     */
    public Builder setStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      status_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object remarks_ = "";
    /**
     * <code>optional string remarks = 2;</code>
     */
    public boolean hasRemarks() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string remarks = 2;</code>
     */
    public java.lang.String getRemarks() {
      java.lang.Object ref = remarks_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          remarks_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string remarks = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRemarksBytes() {
      java.lang.Object ref = remarks_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        remarks_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string remarks = 2;</code>
     */
    public Builder setRemarks(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      remarks_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string remarks = 2;</code>
     */
    public Builder clearRemarks() {
      bitField0_ = (bitField0_ & ~0x00000002);
      remarks_ = getDefaultInstance().getRemarks();
      onChanged();
      return this;
    }
    /**
     * <code>optional string remarks = 2;</code>
     */
    public Builder setRemarksBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      remarks_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.bcasekuritas.rabbitmq.proto.news.CaRight> caRightData_ =
      java.util.Collections.emptyList();
    private void ensureCaRightDataIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        caRightData_ = new java.util.ArrayList<com.bcasekuritas.rabbitmq.proto.news.CaRight>(caRightData_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.bcasekuritas.rabbitmq.proto.news.CaRight, com.bcasekuritas.rabbitmq.proto.news.CaRight.Builder, com.bcasekuritas.rabbitmq.proto.news.CaRightOrBuilder> caRightDataBuilder_;

    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.news.CaRight caRightData = 3;</code>
     */
    public java.util.List<com.bcasekuritas.rabbitmq.proto.news.CaRight> getCaRightDataList() {
      if (caRightDataBuilder_ == null) {
        return java.util.Collections.unmodifiableList(caRightData_);
      } else {
        return caRightDataBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.news.CaRight caRightData = 3;</code>
     */
    public int getCaRightDataCount() {
      if (caRightDataBuilder_ == null) {
        return caRightData_.size();
      } else {
        return caRightDataBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.news.CaRight caRightData = 3;</code>
     */
    public com.bcasekuritas.rabbitmq.proto.news.CaRight getCaRightData(int index) {
      if (caRightDataBuilder_ == null) {
        return caRightData_.get(index);
      } else {
        return caRightDataBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.news.CaRight caRightData = 3;</code>
     */
    public Builder setCaRightData(
        int index, com.bcasekuritas.rabbitmq.proto.news.CaRight value) {
      if (caRightDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCaRightDataIsMutable();
        caRightData_.set(index, value);
        onChanged();
      } else {
        caRightDataBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.news.CaRight caRightData = 3;</code>
     */
    public Builder setCaRightData(
        int index, com.bcasekuritas.rabbitmq.proto.news.CaRight.Builder builderForValue) {
      if (caRightDataBuilder_ == null) {
        ensureCaRightDataIsMutable();
        caRightData_.set(index, builderForValue.build());
        onChanged();
      } else {
        caRightDataBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.news.CaRight caRightData = 3;</code>
     */
    public Builder addCaRightData(com.bcasekuritas.rabbitmq.proto.news.CaRight value) {
      if (caRightDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCaRightDataIsMutable();
        caRightData_.add(value);
        onChanged();
      } else {
        caRightDataBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.news.CaRight caRightData = 3;</code>
     */
    public Builder addCaRightData(
        int index, com.bcasekuritas.rabbitmq.proto.news.CaRight value) {
      if (caRightDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCaRightDataIsMutable();
        caRightData_.add(index, value);
        onChanged();
      } else {
        caRightDataBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.news.CaRight caRightData = 3;</code>
     */
    public Builder addCaRightData(
        com.bcasekuritas.rabbitmq.proto.news.CaRight.Builder builderForValue) {
      if (caRightDataBuilder_ == null) {
        ensureCaRightDataIsMutable();
        caRightData_.add(builderForValue.build());
        onChanged();
      } else {
        caRightDataBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.news.CaRight caRightData = 3;</code>
     */
    public Builder addCaRightData(
        int index, com.bcasekuritas.rabbitmq.proto.news.CaRight.Builder builderForValue) {
      if (caRightDataBuilder_ == null) {
        ensureCaRightDataIsMutable();
        caRightData_.add(index, builderForValue.build());
        onChanged();
      } else {
        caRightDataBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.news.CaRight caRightData = 3;</code>
     */
    public Builder addAllCaRightData(
        java.lang.Iterable<? extends com.bcasekuritas.rabbitmq.proto.news.CaRight> values) {
      if (caRightDataBuilder_ == null) {
        ensureCaRightDataIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, caRightData_);
        onChanged();
      } else {
        caRightDataBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.news.CaRight caRightData = 3;</code>
     */
    public Builder clearCaRightData() {
      if (caRightDataBuilder_ == null) {
        caRightData_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        caRightDataBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.news.CaRight caRightData = 3;</code>
     */
    public Builder removeCaRightData(int index) {
      if (caRightDataBuilder_ == null) {
        ensureCaRightDataIsMutable();
        caRightData_.remove(index);
        onChanged();
      } else {
        caRightDataBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.news.CaRight caRightData = 3;</code>
     */
    public com.bcasekuritas.rabbitmq.proto.news.CaRight.Builder getCaRightDataBuilder(
        int index) {
      return getCaRightDataFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.news.CaRight caRightData = 3;</code>
     */
    public com.bcasekuritas.rabbitmq.proto.news.CaRightOrBuilder getCaRightDataOrBuilder(
        int index) {
      if (caRightDataBuilder_ == null) {
        return caRightData_.get(index);  } else {
        return caRightDataBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.news.CaRight caRightData = 3;</code>
     */
    public java.util.List<? extends com.bcasekuritas.rabbitmq.proto.news.CaRightOrBuilder> 
         getCaRightDataOrBuilderList() {
      if (caRightDataBuilder_ != null) {
        return caRightDataBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(caRightData_);
      }
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.news.CaRight caRightData = 3;</code>
     */
    public com.bcasekuritas.rabbitmq.proto.news.CaRight.Builder addCaRightDataBuilder() {
      return getCaRightDataFieldBuilder().addBuilder(
          com.bcasekuritas.rabbitmq.proto.news.CaRight.getDefaultInstance());
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.news.CaRight caRightData = 3;</code>
     */
    public com.bcasekuritas.rabbitmq.proto.news.CaRight.Builder addCaRightDataBuilder(
        int index) {
      return getCaRightDataFieldBuilder().addBuilder(
          index, com.bcasekuritas.rabbitmq.proto.news.CaRight.getDefaultInstance());
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.news.CaRight caRightData = 3;</code>
     */
    public java.util.List<com.bcasekuritas.rabbitmq.proto.news.CaRight.Builder> 
         getCaRightDataBuilderList() {
      return getCaRightDataFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.bcasekuritas.rabbitmq.proto.news.CaRight, com.bcasekuritas.rabbitmq.proto.news.CaRight.Builder, com.bcasekuritas.rabbitmq.proto.news.CaRightOrBuilder> 
        getCaRightDataFieldBuilder() {
      if (caRightDataBuilder_ == null) {
        caRightDataBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.bcasekuritas.rabbitmq.proto.news.CaRight, com.bcasekuritas.rabbitmq.proto.news.CaRight.Builder, com.bcasekuritas.rabbitmq.proto.news.CaRightOrBuilder>(
                caRightData_,
                ((bitField0_ & 0x00000004) == 0x00000004),
                getParentForChildren(),
                isClean());
        caRightData_ = null;
      }
      return caRightDataBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:com.bcasekuritas.rabbitmq.proto.news.CaRightResponse)
  }

  static {
    defaultInstance = new CaRightResponse(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:com.bcasekuritas.rabbitmq.proto.news.CaRightResponse)
}

