// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: News.proto

package com.bcasekuritas.rabbitmq.proto.news;

/**
 * Protobuf type {@code com.bcasekuritas.rabbitmq.proto.news.CaRversResponse}
 */
public final class CaRversResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.bcasekuritas.rabbitmq.proto.news.CaRversResponse)
    CaRversResponseOrBuilder {
  // Use CaRversResponse.newBuilder() to construct.
  private CaRversResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private CaRversResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final CaRversResponse defaultInstance;
  public static CaRversResponse getDefaultInstance() {
    return defaultInstance;
  }

  public CaRversResponse getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private CaRversResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000001;
            status_ = bs;
            break;
          }
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000002;
            remarks_ = bs;
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              caRversData_ = new java.util.ArrayList<com.bcasekuritas.rabbitmq.proto.news.CaRvers>();
              mutable_bitField0_ |= 0x00000004;
            }
            caRversData_.add(input.readMessage(com.bcasekuritas.rabbitmq.proto.news.CaRvers.PARSER, extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        caRversData_ = java.util.Collections.unmodifiableList(caRversData_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bcasekuritas.rabbitmq.proto.news.News.internal_static_com_bcasekuritas_rabbitmq_proto_news_CaRversResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bcasekuritas.rabbitmq.proto.news.News.internal_static_com_bcasekuritas_rabbitmq_proto_news_CaRversResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bcasekuritas.rabbitmq.proto.news.CaRversResponse.class, com.bcasekuritas.rabbitmq.proto.news.CaRversResponse.Builder.class);
  }

  public static com.google.protobuf.Parser<CaRversResponse> PARSER =
      new com.google.protobuf.AbstractParser<CaRversResponse>() {
    public CaRversResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CaRversResponse(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<CaRversResponse> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  public static final int STATUS_FIELD_NUMBER = 1;
  private java.lang.Object status_;
  /**
   * <code>optional string status = 1;</code>
   */
  public boolean hasStatus() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional string status = 1;</code>
   */
  public java.lang.String getStatus() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        status_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string status = 1;</code>
   */
  public com.google.protobuf.ByteString
      getStatusBytes() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      status_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REMARKS_FIELD_NUMBER = 2;
  private java.lang.Object remarks_;
  /**
   * <code>optional string remarks = 2;</code>
   */
  public boolean hasRemarks() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional string remarks = 2;</code>
   */
  public java.lang.String getRemarks() {
    java.lang.Object ref = remarks_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        remarks_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string remarks = 2;</code>
   */
  public com.google.protobuf.ByteString
      getRemarksBytes() {
    java.lang.Object ref = remarks_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      remarks_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CARVERSDATA_FIELD_NUMBER = 3;
  private java.util.List<com.bcasekuritas.rabbitmq.proto.news.CaRvers> caRversData_;
  /**
   * <code>repeated .com.bcasekuritas.rabbitmq.proto.news.CaRvers caRversData = 3;</code>
   */
  public java.util.List<com.bcasekuritas.rabbitmq.proto.news.CaRvers> getCaRversDataList() {
    return caRversData_;
  }
  /**
   * <code>repeated .com.bcasekuritas.rabbitmq.proto.news.CaRvers caRversData = 3;</code>
   */
  public java.util.List<? extends com.bcasekuritas.rabbitmq.proto.news.CaRversOrBuilder> 
      getCaRversDataOrBuilderList() {
    return caRversData_;
  }
  /**
   * <code>repeated .com.bcasekuritas.rabbitmq.proto.news.CaRvers caRversData = 3;</code>
   */
  public int getCaRversDataCount() {
    return caRversData_.size();
  }
  /**
   * <code>repeated .com.bcasekuritas.rabbitmq.proto.news.CaRvers caRversData = 3;</code>
   */
  public com.bcasekuritas.rabbitmq.proto.news.CaRvers getCaRversData(int index) {
    return caRversData_.get(index);
  }
  /**
   * <code>repeated .com.bcasekuritas.rabbitmq.proto.news.CaRvers caRversData = 3;</code>
   */
  public com.bcasekuritas.rabbitmq.proto.news.CaRversOrBuilder getCaRversDataOrBuilder(
      int index) {
    return caRversData_.get(index);
  }

  private void initFields() {
    status_ = "";
    remarks_ = "";
    caRversData_ = java.util.Collections.emptyList();
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeBytes(1, getStatusBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeBytes(2, getRemarksBytes());
    }
    for (int i = 0; i < caRversData_.size(); i++) {
      output.writeMessage(3, caRversData_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, getStatusBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, getRemarksBytes());
    }
    for (int i = 0; i < caRversData_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, caRversData_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static com.bcasekuritas.rabbitmq.proto.news.CaRversResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bcasekuritas.rabbitmq.proto.news.CaRversResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bcasekuritas.rabbitmq.proto.news.CaRversResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bcasekuritas.rabbitmq.proto.news.CaRversResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bcasekuritas.rabbitmq.proto.news.CaRversResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.bcasekuritas.rabbitmq.proto.news.CaRversResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.bcasekuritas.rabbitmq.proto.news.CaRversResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.bcasekuritas.rabbitmq.proto.news.CaRversResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.bcasekuritas.rabbitmq.proto.news.CaRversResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.bcasekuritas.rabbitmq.proto.news.CaRversResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.bcasekuritas.rabbitmq.proto.news.CaRversResponse prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.bcasekuritas.rabbitmq.proto.news.CaRversResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.bcasekuritas.rabbitmq.proto.news.CaRversResponse)
      com.bcasekuritas.rabbitmq.proto.news.CaRversResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bcasekuritas.rabbitmq.proto.news.News.internal_static_com_bcasekuritas_rabbitmq_proto_news_CaRversResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bcasekuritas.rabbitmq.proto.news.News.internal_static_com_bcasekuritas_rabbitmq_proto_news_CaRversResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bcasekuritas.rabbitmq.proto.news.CaRversResponse.class, com.bcasekuritas.rabbitmq.proto.news.CaRversResponse.Builder.class);
    }

    // Construct using com.bcasekuritas.rabbitmq.proto.news.CaRversResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getCaRversDataFieldBuilder();
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      status_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      remarks_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      if (caRversDataBuilder_ == null) {
        caRversData_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        caRversDataBuilder_.clear();
      }
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bcasekuritas.rabbitmq.proto.news.News.internal_static_com_bcasekuritas_rabbitmq_proto_news_CaRversResponse_descriptor;
    }

    public com.bcasekuritas.rabbitmq.proto.news.CaRversResponse getDefaultInstanceForType() {
      return com.bcasekuritas.rabbitmq.proto.news.CaRversResponse.getDefaultInstance();
    }

    public com.bcasekuritas.rabbitmq.proto.news.CaRversResponse build() {
      com.bcasekuritas.rabbitmq.proto.news.CaRversResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.bcasekuritas.rabbitmq.proto.news.CaRversResponse buildPartial() {
      com.bcasekuritas.rabbitmq.proto.news.CaRversResponse result = new com.bcasekuritas.rabbitmq.proto.news.CaRversResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.status_ = status_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.remarks_ = remarks_;
      if (caRversDataBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          caRversData_ = java.util.Collections.unmodifiableList(caRversData_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.caRversData_ = caRversData_;
      } else {
        result.caRversData_ = caRversDataBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bcasekuritas.rabbitmq.proto.news.CaRversResponse) {
        return mergeFrom((com.bcasekuritas.rabbitmq.proto.news.CaRversResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bcasekuritas.rabbitmq.proto.news.CaRversResponse other) {
      if (other == com.bcasekuritas.rabbitmq.proto.news.CaRversResponse.getDefaultInstance()) return this;
      if (other.hasStatus()) {
        bitField0_ |= 0x00000001;
        status_ = other.status_;
        onChanged();
      }
      if (other.hasRemarks()) {
        bitField0_ |= 0x00000002;
        remarks_ = other.remarks_;
        onChanged();
      }
      if (caRversDataBuilder_ == null) {
        if (!other.caRversData_.isEmpty()) {
          if (caRversData_.isEmpty()) {
            caRversData_ = other.caRversData_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureCaRversDataIsMutable();
            caRversData_.addAll(other.caRversData_);
          }
          onChanged();
        }
      } else {
        if (!other.caRversData_.isEmpty()) {
          if (caRversDataBuilder_.isEmpty()) {
            caRversDataBuilder_.dispose();
            caRversDataBuilder_ = null;
            caRversData_ = other.caRversData_;
            bitField0_ = (bitField0_ & ~0x00000004);
            caRversDataBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getCaRversDataFieldBuilder() : null;
          } else {
            caRversDataBuilder_.addAllMessages(other.caRversData_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.bcasekuritas.rabbitmq.proto.news.CaRversResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.bcasekuritas.rabbitmq.proto.news.CaRversResponse) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object status_ = "";
    /**
     * <code>optional string status = 1;</code>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string status = 1;</code>
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          status_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string status = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string status = 1;</code>
     */
    public Builder setStatus(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string status = 1;</code>
     */
    public Builder clearStatus() {
      bitField0_ = (bitField0_ & ~0x00000001);
      status_ = getDefaultInstance().getStatus();
      onChanged();
      return this;
    }
    /**
     * <code>optional string status = 1;</code>
     */
    public Builder setStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      status_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object remarks_ = "";
    /**
     * <code>optional string remarks = 2;</code>
     */
    public boolean hasRemarks() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string remarks = 2;</code>
     */
    public java.lang.String getRemarks() {
      java.lang.Object ref = remarks_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          remarks_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string remarks = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRemarksBytes() {
      java.lang.Object ref = remarks_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        remarks_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string remarks = 2;</code>
     */
    public Builder setRemarks(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      remarks_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string remarks = 2;</code>
     */
    public Builder clearRemarks() {
      bitField0_ = (bitField0_ & ~0x00000002);
      remarks_ = getDefaultInstance().getRemarks();
      onChanged();
      return this;
    }
    /**
     * <code>optional string remarks = 2;</code>
     */
    public Builder setRemarksBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      remarks_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.bcasekuritas.rabbitmq.proto.news.CaRvers> caRversData_ =
      java.util.Collections.emptyList();
    private void ensureCaRversDataIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        caRversData_ = new java.util.ArrayList<com.bcasekuritas.rabbitmq.proto.news.CaRvers>(caRversData_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.bcasekuritas.rabbitmq.proto.news.CaRvers, com.bcasekuritas.rabbitmq.proto.news.CaRvers.Builder, com.bcasekuritas.rabbitmq.proto.news.CaRversOrBuilder> caRversDataBuilder_;

    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.news.CaRvers caRversData = 3;</code>
     */
    public java.util.List<com.bcasekuritas.rabbitmq.proto.news.CaRvers> getCaRversDataList() {
      if (caRversDataBuilder_ == null) {
        return java.util.Collections.unmodifiableList(caRversData_);
      } else {
        return caRversDataBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.news.CaRvers caRversData = 3;</code>
     */
    public int getCaRversDataCount() {
      if (caRversDataBuilder_ == null) {
        return caRversData_.size();
      } else {
        return caRversDataBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.news.CaRvers caRversData = 3;</code>
     */
    public com.bcasekuritas.rabbitmq.proto.news.CaRvers getCaRversData(int index) {
      if (caRversDataBuilder_ == null) {
        return caRversData_.get(index);
      } else {
        return caRversDataBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.news.CaRvers caRversData = 3;</code>
     */
    public Builder setCaRversData(
        int index, com.bcasekuritas.rabbitmq.proto.news.CaRvers value) {
      if (caRversDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCaRversDataIsMutable();
        caRversData_.set(index, value);
        onChanged();
      } else {
        caRversDataBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.news.CaRvers caRversData = 3;</code>
     */
    public Builder setCaRversData(
        int index, com.bcasekuritas.rabbitmq.proto.news.CaRvers.Builder builderForValue) {
      if (caRversDataBuilder_ == null) {
        ensureCaRversDataIsMutable();
        caRversData_.set(index, builderForValue.build());
        onChanged();
      } else {
        caRversDataBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.news.CaRvers caRversData = 3;</code>
     */
    public Builder addCaRversData(com.bcasekuritas.rabbitmq.proto.news.CaRvers value) {
      if (caRversDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCaRversDataIsMutable();
        caRversData_.add(value);
        onChanged();
      } else {
        caRversDataBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.news.CaRvers caRversData = 3;</code>
     */
    public Builder addCaRversData(
        int index, com.bcasekuritas.rabbitmq.proto.news.CaRvers value) {
      if (caRversDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCaRversDataIsMutable();
        caRversData_.add(index, value);
        onChanged();
      } else {
        caRversDataBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.news.CaRvers caRversData = 3;</code>
     */
    public Builder addCaRversData(
        com.bcasekuritas.rabbitmq.proto.news.CaRvers.Builder builderForValue) {
      if (caRversDataBuilder_ == null) {
        ensureCaRversDataIsMutable();
        caRversData_.add(builderForValue.build());
        onChanged();
      } else {
        caRversDataBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.news.CaRvers caRversData = 3;</code>
     */
    public Builder addCaRversData(
        int index, com.bcasekuritas.rabbitmq.proto.news.CaRvers.Builder builderForValue) {
      if (caRversDataBuilder_ == null) {
        ensureCaRversDataIsMutable();
        caRversData_.add(index, builderForValue.build());
        onChanged();
      } else {
        caRversDataBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.news.CaRvers caRversData = 3;</code>
     */
    public Builder addAllCaRversData(
        java.lang.Iterable<? extends com.bcasekuritas.rabbitmq.proto.news.CaRvers> values) {
      if (caRversDataBuilder_ == null) {
        ensureCaRversDataIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, caRversData_);
        onChanged();
      } else {
        caRversDataBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.news.CaRvers caRversData = 3;</code>
     */
    public Builder clearCaRversData() {
      if (caRversDataBuilder_ == null) {
        caRversData_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        caRversDataBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.news.CaRvers caRversData = 3;</code>
     */
    public Builder removeCaRversData(int index) {
      if (caRversDataBuilder_ == null) {
        ensureCaRversDataIsMutable();
        caRversData_.remove(index);
        onChanged();
      } else {
        caRversDataBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.news.CaRvers caRversData = 3;</code>
     */
    public com.bcasekuritas.rabbitmq.proto.news.CaRvers.Builder getCaRversDataBuilder(
        int index) {
      return getCaRversDataFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.news.CaRvers caRversData = 3;</code>
     */
    public com.bcasekuritas.rabbitmq.proto.news.CaRversOrBuilder getCaRversDataOrBuilder(
        int index) {
      if (caRversDataBuilder_ == null) {
        return caRversData_.get(index);  } else {
        return caRversDataBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.news.CaRvers caRversData = 3;</code>
     */
    public java.util.List<? extends com.bcasekuritas.rabbitmq.proto.news.CaRversOrBuilder> 
         getCaRversDataOrBuilderList() {
      if (caRversDataBuilder_ != null) {
        return caRversDataBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(caRversData_);
      }
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.news.CaRvers caRversData = 3;</code>
     */
    public com.bcasekuritas.rabbitmq.proto.news.CaRvers.Builder addCaRversDataBuilder() {
      return getCaRversDataFieldBuilder().addBuilder(
          com.bcasekuritas.rabbitmq.proto.news.CaRvers.getDefaultInstance());
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.news.CaRvers caRversData = 3;</code>
     */
    public com.bcasekuritas.rabbitmq.proto.news.CaRvers.Builder addCaRversDataBuilder(
        int index) {
      return getCaRversDataFieldBuilder().addBuilder(
          index, com.bcasekuritas.rabbitmq.proto.news.CaRvers.getDefaultInstance());
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.news.CaRvers caRversData = 3;</code>
     */
    public java.util.List<com.bcasekuritas.rabbitmq.proto.news.CaRvers.Builder> 
         getCaRversDataBuilderList() {
      return getCaRversDataFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.bcasekuritas.rabbitmq.proto.news.CaRvers, com.bcasekuritas.rabbitmq.proto.news.CaRvers.Builder, com.bcasekuritas.rabbitmq.proto.news.CaRversOrBuilder> 
        getCaRversDataFieldBuilder() {
      if (caRversDataBuilder_ == null) {
        caRversDataBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.bcasekuritas.rabbitmq.proto.news.CaRvers, com.bcasekuritas.rabbitmq.proto.news.CaRvers.Builder, com.bcasekuritas.rabbitmq.proto.news.CaRversOrBuilder>(
                caRversData_,
                ((bitField0_ & 0x00000004) == 0x00000004),
                getParentForChildren(),
                isClean());
        caRversData_ = null;
      }
      return caRversDataBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:com.bcasekuritas.rabbitmq.proto.news.CaRversResponse)
  }

  static {
    defaultInstance = new CaRversResponse(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:com.bcasekuritas.rabbitmq.proto.news.CaRversResponse)
}

