// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: News.proto

package com.bcasekuritas.rabbitmq.proto.news;

public interface CaRversOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.bcasekuritas.rabbitmq.proto.news.CaRvers)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string rversCode = 1;</code>
   */
  boolean hasRversCode();
  /**
   * <code>optional string rversCode = 1;</code>
   */
  java.lang.String getRversCode();
  /**
   * <code>optional string rversCode = 1;</code>
   */
  com.google.protobuf.ByteString
      getRversCodeBytes();

  /**
   * <code>optional string rversOldRatioShare = 2;</code>
   */
  boolean hasRversOldRatioShare();
  /**
   * <code>optional string rversOldRatioShare = 2;</code>
   */
  java.lang.String getRversOldRatioShare();
  /**
   * <code>optional string rversOldRatioShare = 2;</code>
   */
  com.google.protobuf.ByteString
      getRversOldRatioShareBytes();

  /**
   * <code>optional string rversNewRatioShare = 3;</code>
   */
  boolean hasRversNewRatioShare();
  /**
   * <code>optional string rversNewRatioShare = 3;</code>
   */
  java.lang.String getRversNewRatioShare();
  /**
   * <code>optional string rversNewRatioShare = 3;</code>
   */
  com.google.protobuf.ByteString
      getRversNewRatioShareBytes();

  /**
   * <code>optional string rversNewParValue = 4;</code>
   */
  boolean hasRversNewParValue();
  /**
   * <code>optional string rversNewParValue = 4;</code>
   */
  java.lang.String getRversNewParValue();
  /**
   * <code>optional string rversNewParValue = 4;</code>
   */
  com.google.protobuf.ByteString
      getRversNewParValueBytes();

  /**
   * <code>optional uint64 rversTradeDt = 5;</code>
   */
  boolean hasRversTradeDt();
  /**
   * <code>optional uint64 rversTradeDt = 5;</code>
   */
  long getRversTradeDt();

  /**
   * <code>optional uint64 rversRecordDt = 6;</code>
   */
  boolean hasRversRecordDt();
  /**
   * <code>optional uint64 rversRecordDt = 6;</code>
   */
  long getRversRecordDt();

  /**
   * <code>optional string rversShare = 7;</code>
   */
  boolean hasRversShare();
  /**
   * <code>optional string rversShare = 7;</code>
   */
  java.lang.String getRversShare();
  /**
   * <code>optional string rversShare = 7;</code>
   */
  com.google.protobuf.ByteString
      getRversShareBytes();

  /**
   * <code>optional string rversRemark = 8;</code>
   */
  boolean hasRversRemark();
  /**
   * <code>optional string rversRemark = 8;</code>
   */
  java.lang.String getRversRemark();
  /**
   * <code>optional string rversRemark = 8;</code>
   */
  com.google.protobuf.ByteString
      getRversRemarkBytes();

  /**
   * <code>optional uint64 createdDate = 9;</code>
   */
  boolean hasCreatedDate();
  /**
   * <code>optional uint64 createdDate = 9;</code>
   */
  long getCreatedDate();

  /**
   * <code>optional uint64 revisedDate = 10;</code>
   */
  boolean hasRevisedDate();
  /**
   * <code>optional uint64 revisedDate = 10;</code>
   */
  long getRevisedDate();
}
