// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: News.proto

package com.bcasekuritas.rabbitmq.proto.news;

public interface SaveAssetsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.bcasekuritas.rabbitmq.proto.news.SaveAssetsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string userId = 1;</code>
   */
  boolean hasUserId();
  /**
   * <code>required string userId = 1;</code>
   */
  java.lang.String getUserId();
  /**
   * <code>required string userId = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>optional string sessionId = 2;</code>
   */
  boolean hasSessionId();
  /**
   * <code>optional string sessionId = 2;</code>
   */
  java.lang.String getSessionId();
  /**
   * <code>optional string sessionId = 2;</code>
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();

  /**
   * <code>optional string assetTitle = 3;</code>
   */
  boolean hasAssetTitle();
  /**
   * <code>optional string assetTitle = 3;</code>
   */
  java.lang.String getAssetTitle();
  /**
   * <code>optional string assetTitle = 3;</code>
   */
  com.google.protobuf.ByteString
      getAssetTitleBytes();

  /**
   * <code>optional string assetData = 4;</code>
   */
  boolean hasAssetData();
  /**
   * <code>optional string assetData = 4;</code>
   */
  java.lang.String getAssetData();
  /**
   * <code>optional string assetData = 4;</code>
   */
  com.google.protobuf.ByteString
      getAssetDataBytes();

  /**
   * <code>optional string assetDataContentType = 5;</code>
   */
  boolean hasAssetDataContentType();
  /**
   * <code>optional string assetDataContentType = 5;</code>
   */
  java.lang.String getAssetDataContentType();
  /**
   * <code>optional string assetDataContentType = 5;</code>
   */
  com.google.protobuf.ByteString
      getAssetDataContentTypeBytes();

  /**
   * <code>required uint32 requestType = 6;</code>
   *
   * <pre>
   * 1 = icon, 2 = logo
   * </pre>
   */
  boolean hasRequestType();
  /**
   * <code>required uint32 requestType = 6;</code>
   *
   * <pre>
   * 1 = icon, 2 = logo
   * </pre>
   */
  int getRequestType();
}
