// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Bcasolt.proto

package com.bcasekuritas.rabbitmq.proto.bcas;

public interface AccMfPosResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.bcasekuritas.rabbitmq.proto.bcas.AccMfPosResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required uint32 status = 1;</code>
   *
   * <pre>
   *0="OK", 1="Reject"
   * </pre>
   */
  boolean hasStatus();
  /**
   * <code>required uint32 status = 1;</code>
   *
   * <pre>
   *0="OK", 1="Reject"
   * </pre>
   */
  int getStatus();

  /**
   * <code>repeated .com.bcasekuritas.rabbitmq.proto.bcas.AccMfPos accsMfPos = 2;</code>
   */
  java.util.List<com.bcasekuritas.rabbitmq.proto.bcas.AccMfPos> 
      getAccsMfPosList();
  /**
   * <code>repeated .com.bcasekuritas.rabbitmq.proto.bcas.AccMfPos accsMfPos = 2;</code>
   */
  com.bcasekuritas.rabbitmq.proto.bcas.AccMfPos getAccsMfPos(int index);
  /**
   * <code>repeated .com.bcasekuritas.rabbitmq.proto.bcas.AccMfPos accsMfPos = 2;</code>
   */
  int getAccsMfPosCount();
  /**
   * <code>repeated .com.bcasekuritas.rabbitmq.proto.bcas.AccMfPos accsMfPos = 2;</code>
   */
  java.util.List<? extends com.bcasekuritas.rabbitmq.proto.bcas.AccMfPosOrBuilder> 
      getAccsMfPosOrBuilderList();
  /**
   * <code>repeated .com.bcasekuritas.rabbitmq.proto.bcas.AccMfPos accsMfPos = 2;</code>
   */
  com.bcasekuritas.rabbitmq.proto.bcas.AccMfPosOrBuilder getAccsMfPosOrBuilder(
      int index);

  /**
   * <code>optional string description = 3;</code>
   */
  boolean hasDescription();
  /**
   * <code>optional string description = 3;</code>
   */
  java.lang.String getDescription();
  /**
   * <code>optional string description = 3;</code>
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();
}
