// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Bcasolt.proto

package com.bcasekuritas.rabbitmq.proto.bcas;

public interface AdvancedCriteriaListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.bcasekuritas.rabbitmq.proto.bcas.AdvancedCriteriaList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.bcasekuritas.rabbitmq.proto.bcas.AdvancedCriteria advancedCriteria = 1;</code>
   */
  java.util.List<com.bcasekuritas.rabbitmq.proto.bcas.AdvancedCriteria> 
      getAdvancedCriteriaList();
  /**
   * <code>repeated .com.bcasekuritas.rabbitmq.proto.bcas.AdvancedCriteria advancedCriteria = 1;</code>
   */
  com.bcasekuritas.rabbitmq.proto.bcas.AdvancedCriteria getAdvancedCriteria(int index);
  /**
   * <code>repeated .com.bcasekuritas.rabbitmq.proto.bcas.AdvancedCriteria advancedCriteria = 1;</code>
   */
  int getAdvancedCriteriaCount();
  /**
   * <code>repeated .com.bcasekuritas.rabbitmq.proto.bcas.AdvancedCriteria advancedCriteria = 1;</code>
   */
  java.util.List<? extends com.bcasekuritas.rabbitmq.proto.bcas.AdvancedCriteriaOrBuilder> 
      getAdvancedCriteriaOrBuilderList();
  /**
   * <code>repeated .com.bcasekuritas.rabbitmq.proto.bcas.AdvancedCriteria advancedCriteria = 1;</code>
   */
  com.bcasekuritas.rabbitmq.proto.bcas.AdvancedCriteriaOrBuilder getAdvancedCriteriaOrBuilder(
      int index);
}
