// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Bcasolt.proto

package com.bcasekuritas.rabbitmq.proto.bcas;

public interface BankCustodiOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.bcasekuritas.rabbitmq.proto.bcas.BankCustodi)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string createdBy = 1;</code>
   */
  boolean hasCreatedBy();
  /**
   * <code>optional string createdBy = 1;</code>
   */
  java.lang.String getCreatedBy();
  /**
   * <code>optional string createdBy = 1;</code>
   */
  com.google.protobuf.ByteString
      getCreatedByBytes();

  /**
   * <code>optional string createdDate = 2;</code>
   */
  boolean hasCreatedDate();
  /**
   * <code>optional string createdDate = 2;</code>
   */
  java.lang.String getCreatedDate();
  /**
   * <code>optional string createdDate = 2;</code>
   */
  com.google.protobuf.ByteString
      getCreatedDateBytes();

  /**
   * <code>optional uint32 id = 3;</code>
   */
  boolean hasId();
  /**
   * <code>optional uint32 id = 3;</code>
   */
  int getId();

  /**
   * <code>optional string kodeCustodi = 4;</code>
   */
  boolean hasKodeCustodi();
  /**
   * <code>optional string kodeCustodi = 4;</code>
   */
  java.lang.String getKodeCustodi();
  /**
   * <code>optional string kodeCustodi = 4;</code>
   */
  com.google.protobuf.ByteString
      getKodeCustodiBytes();

  /**
   * <code>optional string lastmodifiedBy = 5;</code>
   */
  boolean hasLastmodifiedBy();
  /**
   * <code>optional string lastmodifiedBy = 5;</code>
   */
  java.lang.String getLastmodifiedBy();
  /**
   * <code>optional string lastmodifiedBy = 5;</code>
   */
  com.google.protobuf.ByteString
      getLastmodifiedByBytes();

  /**
   * <code>optional string lasModifiedDate = 6;</code>
   */
  boolean hasLasModifiedDate();
  /**
   * <code>optional string lasModifiedDate = 6;</code>
   */
  java.lang.String getLasModifiedDate();
  /**
   * <code>optional string lasModifiedDate = 6;</code>
   */
  com.google.protobuf.ByteString
      getLasModifiedDateBytes();

  /**
   * <code>optional string namaCustodi = 7;</code>
   */
  boolean hasNamaCustodi();
  /**
   * <code>optional string namaCustodi = 7;</code>
   */
  java.lang.String getNamaCustodi();
  /**
   * <code>optional string namaCustodi = 7;</code>
   */
  com.google.protobuf.ByteString
      getNamaCustodiBytes();
}
