// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Bcasolt.proto

package com.bcasekuritas.rabbitmq.proto.bcas;

/**
 * Protobuf type {@code com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoResponse}
 */
public final class IpoBondInfoResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoResponse)
    IpoBondInfoResponseOrBuilder {
  // Use IpoBondInfoResponse.newBuilder() to construct.
  private IpoBondInfoResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private IpoBondInfoResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final IpoBondInfoResponse defaultInstance;
  public static IpoBondInfoResponse getDefaultInstance() {
    return defaultInstance;
  }

  public IpoBondInfoResponse getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private IpoBondInfoResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            bitField0_ |= 0x00000001;
            status_ = input.readUInt32();
            break;
          }
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000002;
            remarks_ = bs;
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              ipoBondInfoData_ = new java.util.ArrayList<com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoData>();
              mutable_bitField0_ |= 0x00000004;
            }
            ipoBondInfoData_.add(input.readMessage(com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoData.PARSER, extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        ipoBondInfoData_ = java.util.Collections.unmodifiableList(ipoBondInfoData_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bcasekuritas.rabbitmq.proto.bcas.Bcasolt.internal_static_com_bcasekuritas_rabbitmq_proto_bcas_IpoBondInfoResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bcasekuritas.rabbitmq.proto.bcas.Bcasolt.internal_static_com_bcasekuritas_rabbitmq_proto_bcas_IpoBondInfoResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoResponse.class, com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoResponse.Builder.class);
  }

  public static com.google.protobuf.Parser<IpoBondInfoResponse> PARSER =
      new com.google.protobuf.AbstractParser<IpoBondInfoResponse>() {
    public IpoBondInfoResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new IpoBondInfoResponse(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<IpoBondInfoResponse> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  public static final int STATUS_FIELD_NUMBER = 1;
  private int status_;
  /**
   * <code>required uint32 status = 1;</code>
   */
  public boolean hasStatus() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required uint32 status = 1;</code>
   */
  public int getStatus() {
    return status_;
  }

  public static final int REMARKS_FIELD_NUMBER = 2;
  private java.lang.Object remarks_;
  /**
   * <code>optional string remarks = 2;</code>
   */
  public boolean hasRemarks() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional string remarks = 2;</code>
   */
  public java.lang.String getRemarks() {
    java.lang.Object ref = remarks_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        remarks_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string remarks = 2;</code>
   */
  public com.google.protobuf.ByteString
      getRemarksBytes() {
    java.lang.Object ref = remarks_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      remarks_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IPOBONDINFODATA_FIELD_NUMBER = 3;
  private java.util.List<com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoData> ipoBondInfoData_;
  /**
   * <code>repeated .com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoData ipoBondInfoData = 3;</code>
   */
  public java.util.List<com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoData> getIpoBondInfoDataList() {
    return ipoBondInfoData_;
  }
  /**
   * <code>repeated .com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoData ipoBondInfoData = 3;</code>
   */
  public java.util.List<? extends com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoDataOrBuilder> 
      getIpoBondInfoDataOrBuilderList() {
    return ipoBondInfoData_;
  }
  /**
   * <code>repeated .com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoData ipoBondInfoData = 3;</code>
   */
  public int getIpoBondInfoDataCount() {
    return ipoBondInfoData_.size();
  }
  /**
   * <code>repeated .com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoData ipoBondInfoData = 3;</code>
   */
  public com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoData getIpoBondInfoData(int index) {
    return ipoBondInfoData_.get(index);
  }
  /**
   * <code>repeated .com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoData ipoBondInfoData = 3;</code>
   */
  public com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoDataOrBuilder getIpoBondInfoDataOrBuilder(
      int index) {
    return ipoBondInfoData_.get(index);
  }

  private void initFields() {
    status_ = 0;
    remarks_ = "";
    ipoBondInfoData_ = java.util.Collections.emptyList();
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasStatus()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeUInt32(1, status_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeBytes(2, getRemarksBytes());
    }
    for (int i = 0; i < ipoBondInfoData_.size(); i++) {
      output.writeMessage(3, ipoBondInfoData_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, status_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, getRemarksBytes());
    }
    for (int i = 0; i < ipoBondInfoData_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, ipoBondInfoData_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoResponse prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoResponse)
      com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bcasekuritas.rabbitmq.proto.bcas.Bcasolt.internal_static_com_bcasekuritas_rabbitmq_proto_bcas_IpoBondInfoResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bcasekuritas.rabbitmq.proto.bcas.Bcasolt.internal_static_com_bcasekuritas_rabbitmq_proto_bcas_IpoBondInfoResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoResponse.class, com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoResponse.Builder.class);
    }

    // Construct using com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getIpoBondInfoDataFieldBuilder();
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      status_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      remarks_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      if (ipoBondInfoDataBuilder_ == null) {
        ipoBondInfoData_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        ipoBondInfoDataBuilder_.clear();
      }
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bcasekuritas.rabbitmq.proto.bcas.Bcasolt.internal_static_com_bcasekuritas_rabbitmq_proto_bcas_IpoBondInfoResponse_descriptor;
    }

    public com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoResponse getDefaultInstanceForType() {
      return com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoResponse.getDefaultInstance();
    }

    public com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoResponse build() {
      com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoResponse buildPartial() {
      com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoResponse result = new com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.status_ = status_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.remarks_ = remarks_;
      if (ipoBondInfoDataBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          ipoBondInfoData_ = java.util.Collections.unmodifiableList(ipoBondInfoData_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.ipoBondInfoData_ = ipoBondInfoData_;
      } else {
        result.ipoBondInfoData_ = ipoBondInfoDataBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoResponse) {
        return mergeFrom((com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoResponse other) {
      if (other == com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoResponse.getDefaultInstance()) return this;
      if (other.hasStatus()) {
        setStatus(other.getStatus());
      }
      if (other.hasRemarks()) {
        bitField0_ |= 0x00000002;
        remarks_ = other.remarks_;
        onChanged();
      }
      if (ipoBondInfoDataBuilder_ == null) {
        if (!other.ipoBondInfoData_.isEmpty()) {
          if (ipoBondInfoData_.isEmpty()) {
            ipoBondInfoData_ = other.ipoBondInfoData_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureIpoBondInfoDataIsMutable();
            ipoBondInfoData_.addAll(other.ipoBondInfoData_);
          }
          onChanged();
        }
      } else {
        if (!other.ipoBondInfoData_.isEmpty()) {
          if (ipoBondInfoDataBuilder_.isEmpty()) {
            ipoBondInfoDataBuilder_.dispose();
            ipoBondInfoDataBuilder_ = null;
            ipoBondInfoData_ = other.ipoBondInfoData_;
            bitField0_ = (bitField0_ & ~0x00000004);
            ipoBondInfoDataBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getIpoBondInfoDataFieldBuilder() : null;
          } else {
            ipoBondInfoDataBuilder_.addAllMessages(other.ipoBondInfoData_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasStatus()) {
        
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoResponse) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int status_ ;
    /**
     * <code>required uint32 status = 1;</code>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 status = 1;</code>
     */
    public int getStatus() {
      return status_;
    }
    /**
     * <code>required uint32 status = 1;</code>
     */
    public Builder setStatus(int value) {
      bitField0_ |= 0x00000001;
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required uint32 status = 1;</code>
     */
    public Builder clearStatus() {
      bitField0_ = (bitField0_ & ~0x00000001);
      status_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object remarks_ = "";
    /**
     * <code>optional string remarks = 2;</code>
     */
    public boolean hasRemarks() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string remarks = 2;</code>
     */
    public java.lang.String getRemarks() {
      java.lang.Object ref = remarks_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          remarks_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string remarks = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRemarksBytes() {
      java.lang.Object ref = remarks_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        remarks_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string remarks = 2;</code>
     */
    public Builder setRemarks(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      remarks_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string remarks = 2;</code>
     */
    public Builder clearRemarks() {
      bitField0_ = (bitField0_ & ~0x00000002);
      remarks_ = getDefaultInstance().getRemarks();
      onChanged();
      return this;
    }
    /**
     * <code>optional string remarks = 2;</code>
     */
    public Builder setRemarksBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      remarks_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoData> ipoBondInfoData_ =
      java.util.Collections.emptyList();
    private void ensureIpoBondInfoDataIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        ipoBondInfoData_ = new java.util.ArrayList<com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoData>(ipoBondInfoData_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoData, com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoData.Builder, com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoDataOrBuilder> ipoBondInfoDataBuilder_;

    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoData ipoBondInfoData = 3;</code>
     */
    public java.util.List<com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoData> getIpoBondInfoDataList() {
      if (ipoBondInfoDataBuilder_ == null) {
        return java.util.Collections.unmodifiableList(ipoBondInfoData_);
      } else {
        return ipoBondInfoDataBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoData ipoBondInfoData = 3;</code>
     */
    public int getIpoBondInfoDataCount() {
      if (ipoBondInfoDataBuilder_ == null) {
        return ipoBondInfoData_.size();
      } else {
        return ipoBondInfoDataBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoData ipoBondInfoData = 3;</code>
     */
    public com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoData getIpoBondInfoData(int index) {
      if (ipoBondInfoDataBuilder_ == null) {
        return ipoBondInfoData_.get(index);
      } else {
        return ipoBondInfoDataBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoData ipoBondInfoData = 3;</code>
     */
    public Builder setIpoBondInfoData(
        int index, com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoData value) {
      if (ipoBondInfoDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureIpoBondInfoDataIsMutable();
        ipoBondInfoData_.set(index, value);
        onChanged();
      } else {
        ipoBondInfoDataBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoData ipoBondInfoData = 3;</code>
     */
    public Builder setIpoBondInfoData(
        int index, com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoData.Builder builderForValue) {
      if (ipoBondInfoDataBuilder_ == null) {
        ensureIpoBondInfoDataIsMutable();
        ipoBondInfoData_.set(index, builderForValue.build());
        onChanged();
      } else {
        ipoBondInfoDataBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoData ipoBondInfoData = 3;</code>
     */
    public Builder addIpoBondInfoData(com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoData value) {
      if (ipoBondInfoDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureIpoBondInfoDataIsMutable();
        ipoBondInfoData_.add(value);
        onChanged();
      } else {
        ipoBondInfoDataBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoData ipoBondInfoData = 3;</code>
     */
    public Builder addIpoBondInfoData(
        int index, com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoData value) {
      if (ipoBondInfoDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureIpoBondInfoDataIsMutable();
        ipoBondInfoData_.add(index, value);
        onChanged();
      } else {
        ipoBondInfoDataBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoData ipoBondInfoData = 3;</code>
     */
    public Builder addIpoBondInfoData(
        com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoData.Builder builderForValue) {
      if (ipoBondInfoDataBuilder_ == null) {
        ensureIpoBondInfoDataIsMutable();
        ipoBondInfoData_.add(builderForValue.build());
        onChanged();
      } else {
        ipoBondInfoDataBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoData ipoBondInfoData = 3;</code>
     */
    public Builder addIpoBondInfoData(
        int index, com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoData.Builder builderForValue) {
      if (ipoBondInfoDataBuilder_ == null) {
        ensureIpoBondInfoDataIsMutable();
        ipoBondInfoData_.add(index, builderForValue.build());
        onChanged();
      } else {
        ipoBondInfoDataBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoData ipoBondInfoData = 3;</code>
     */
    public Builder addAllIpoBondInfoData(
        java.lang.Iterable<? extends com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoData> values) {
      if (ipoBondInfoDataBuilder_ == null) {
        ensureIpoBondInfoDataIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, ipoBondInfoData_);
        onChanged();
      } else {
        ipoBondInfoDataBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoData ipoBondInfoData = 3;</code>
     */
    public Builder clearIpoBondInfoData() {
      if (ipoBondInfoDataBuilder_ == null) {
        ipoBondInfoData_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        ipoBondInfoDataBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoData ipoBondInfoData = 3;</code>
     */
    public Builder removeIpoBondInfoData(int index) {
      if (ipoBondInfoDataBuilder_ == null) {
        ensureIpoBondInfoDataIsMutable();
        ipoBondInfoData_.remove(index);
        onChanged();
      } else {
        ipoBondInfoDataBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoData ipoBondInfoData = 3;</code>
     */
    public com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoData.Builder getIpoBondInfoDataBuilder(
        int index) {
      return getIpoBondInfoDataFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoData ipoBondInfoData = 3;</code>
     */
    public com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoDataOrBuilder getIpoBondInfoDataOrBuilder(
        int index) {
      if (ipoBondInfoDataBuilder_ == null) {
        return ipoBondInfoData_.get(index);  } else {
        return ipoBondInfoDataBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoData ipoBondInfoData = 3;</code>
     */
    public java.util.List<? extends com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoDataOrBuilder> 
         getIpoBondInfoDataOrBuilderList() {
      if (ipoBondInfoDataBuilder_ != null) {
        return ipoBondInfoDataBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(ipoBondInfoData_);
      }
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoData ipoBondInfoData = 3;</code>
     */
    public com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoData.Builder addIpoBondInfoDataBuilder() {
      return getIpoBondInfoDataFieldBuilder().addBuilder(
          com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoData.getDefaultInstance());
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoData ipoBondInfoData = 3;</code>
     */
    public com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoData.Builder addIpoBondInfoDataBuilder(
        int index) {
      return getIpoBondInfoDataFieldBuilder().addBuilder(
          index, com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoData.getDefaultInstance());
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoData ipoBondInfoData = 3;</code>
     */
    public java.util.List<com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoData.Builder> 
         getIpoBondInfoDataBuilderList() {
      return getIpoBondInfoDataFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoData, com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoData.Builder, com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoDataOrBuilder> 
        getIpoBondInfoDataFieldBuilder() {
      if (ipoBondInfoDataBuilder_ == null) {
        ipoBondInfoDataBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoData, com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoData.Builder, com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoDataOrBuilder>(
                ipoBondInfoData_,
                ((bitField0_ & 0x00000004) == 0x00000004),
                getParentForChildren(),
                isClean());
        ipoBondInfoData_ = null;
      }
      return ipoBondInfoDataBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoResponse)
  }

  static {
    defaultInstance = new IpoBondInfoResponse(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:com.bcasekuritas.rabbitmq.proto.bcas.IpoBondInfoResponse)
}

