// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Bcasolt.proto

package com.bcasekuritas.rabbitmq.proto.bcas;

public interface IpoEquityOrderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.bcasekuritas.rabbitmq.proto.bcas.IpoEquityOrder)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string clOrderRef = 1;</code>
   */
  boolean hasClOrderRef();
  /**
   * <code>optional string clOrderRef = 1;</code>
   */
  java.lang.String getClOrderRef();
  /**
   * <code>optional string clOrderRef = 1;</code>
   */
  com.google.protobuf.ByteString
      getClOrderRefBytes();

  /**
   * <code>optional string accNo = 2;</code>
   */
  boolean hasAccNo();
  /**
   * <code>optional string accNo = 2;</code>
   */
  java.lang.String getAccNo();
  /**
   * <code>optional string accNo = 2;</code>
   */
  com.google.protobuf.ByteString
      getAccNoBytes();

  /**
   * <code>optional string ipoCode = 3;</code>
   */
  boolean hasIpoCode();
  /**
   * <code>optional string ipoCode = 3;</code>
   */
  java.lang.String getIpoCode();
  /**
   * <code>optional string ipoCode = 3;</code>
   */
  com.google.protobuf.ByteString
      getIpoCodeBytes();

  /**
   * <code>optional double price = 4;</code>
   *
   * <pre>
   * in percentage
   * </pre>
   */
  boolean hasPrice();
  /**
   * <code>optional double price = 4;</code>
   *
   * <pre>
   * in percentage
   * </pre>
   */
  double getPrice();

  /**
   * <code>optional double qty = 5;</code>
   */
  boolean hasQty();
  /**
   * <code>optional double qty = 5;</code>
   */
  double getQty();

  /**
   * <code>optional string desc = 6;</code>
   *
   * <pre>
   * notes
   * </pre>
   */
  boolean hasDesc();
  /**
   * <code>optional string desc = 6;</code>
   *
   * <pre>
   * notes
   * </pre>
   */
  java.lang.String getDesc();
  /**
   * <code>optional string desc = 6;</code>
   *
   * <pre>
   * notes
   * </pre>
   */
  com.google.protobuf.ByteString
      getDescBytes();

  /**
   * <code>optional string inputBy = 7;</code>
   *
   * <pre>
   *userId
   * </pre>
   */
  boolean hasInputBy();
  /**
   * <code>optional string inputBy = 7;</code>
   *
   * <pre>
   *userId
   * </pre>
   */
  java.lang.String getInputBy();
  /**
   * <code>optional string inputBy = 7;</code>
   *
   * <pre>
   *userId
   * </pre>
   */
  com.google.protobuf.ByteString
      getInputByBytes();

  /**
   * <code>optional string ipAddress = 8;</code>
   */
  boolean hasIpAddress();
  /**
   * <code>optional string ipAddress = 8;</code>
   */
  java.lang.String getIpAddress();
  /**
   * <code>optional string ipAddress = 8;</code>
   */
  com.google.protobuf.ByteString
      getIpAddressBytes();

  /**
   * <code>optional uint32 channel = 9;</code>
   *
   * <pre>
   *0=OLT, 1=OMS
   * </pre>
   */
  boolean hasChannel();
  /**
   * <code>optional uint32 channel = 9;</code>
   *
   * <pre>
   *0=OLT, 1=OMS
   * </pre>
   */
  int getChannel();

  /**
   * <code>optional uint32 mediaSource = 10;</code>
   *
   * <pre>
   *0=Android, 1=iOS, 2=HTS, 3=WTS
   * </pre>
   */
  boolean hasMediaSource();
  /**
   * <code>optional uint32 mediaSource = 10;</code>
   *
   * <pre>
   *0=Android, 1=iOS, 2=HTS, 3=WTS
   * </pre>
   */
  int getMediaSource();

  /**
   * <code>optional uint32 typeId = 11;</code>
   *
   * <pre>
   *0=pooling, 1=fixed
   * </pre>
   */
  boolean hasTypeId();
  /**
   * <code>optional uint32 typeId = 11;</code>
   *
   * <pre>
   *0=pooling, 1=fixed
   * </pre>
   */
  int getTypeId();

  /**
   * <code>optional bool isAffiliatedParty = 12;</code>
   */
  boolean hasIsAffiliatedParty();
  /**
   * <code>optional bool isAffiliatedParty = 12;</code>
   */
  boolean getIsAffiliatedParty();

  /**
   * <code>optional bool isEmployee = 13;</code>
   */
  boolean hasIsEmployee();
  /**
   * <code>optional bool isEmployee = 13;</code>
   */
  boolean getIsEmployee();

  /**
   * <code>optional bool isBenefaciaries = 14;</code>
   */
  boolean hasIsBenefaciaries();
  /**
   * <code>optional bool isBenefaciaries = 14;</code>
   */
  boolean getIsBenefaciaries();

  /**
   * <code>optional bool isPremium = 15;</code>
   */
  boolean hasIsPremium();
  /**
   * <code>optional bool isPremium = 15;</code>
   */
  boolean getIsPremium();

  /**
   * <code>optional bool isConfirm = 16;</code>
   */
  boolean hasIsConfirm();
  /**
   * <code>optional bool isConfirm = 16;</code>
   */
  boolean getIsConfirm();

  /**
   * <code>optional bool isEsa = 17;</code>
   */
  boolean hasIsEsa();
  /**
   * <code>optional bool isEsa = 17;</code>
   */
  boolean getIsEsa();
}
