// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Bcasolt.proto

package com.bcasekuritas.rabbitmq.proto.bcas;

/**
 * Protobuf type {@code com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueResponse}
 */
public final class ModifyCheckOverdueResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueResponse)
    ModifyCheckOverdueResponseOrBuilder {
  // Use ModifyCheckOverdueResponse.newBuilder() to construct.
  private ModifyCheckOverdueResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private ModifyCheckOverdueResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final ModifyCheckOverdueResponse defaultInstance;
  public static ModifyCheckOverdueResponse getDefaultInstance() {
    return defaultInstance;
  }

  public ModifyCheckOverdueResponse getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private ModifyCheckOverdueResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            bitField0_ |= 0x00000001;
            status_ = input.readUInt32();
            break;
          }
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000002;
            remarks_ = bs;
            break;
          }
          case 26: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000004;
            accno_ = bs;
            break;
          }
          case 34: {
            com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueData.Builder subBuilder = null;
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
              subBuilder = modifyCheckOverdueData_.toBuilder();
            }
            modifyCheckOverdueData_ = input.readMessage(com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueData.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(modifyCheckOverdueData_);
              modifyCheckOverdueData_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000008;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bcasekuritas.rabbitmq.proto.bcas.Bcasolt.internal_static_com_bcasekuritas_rabbitmq_proto_bcas_ModifyCheckOverdueResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bcasekuritas.rabbitmq.proto.bcas.Bcasolt.internal_static_com_bcasekuritas_rabbitmq_proto_bcas_ModifyCheckOverdueResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueResponse.class, com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueResponse.Builder.class);
  }

  public static com.google.protobuf.Parser<ModifyCheckOverdueResponse> PARSER =
      new com.google.protobuf.AbstractParser<ModifyCheckOverdueResponse>() {
    public ModifyCheckOverdueResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ModifyCheckOverdueResponse(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<ModifyCheckOverdueResponse> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  public static final int STATUS_FIELD_NUMBER = 1;
  private int status_;
  /**
   * <code>required uint32 status = 1;</code>
   */
  public boolean hasStatus() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required uint32 status = 1;</code>
   */
  public int getStatus() {
    return status_;
  }

  public static final int REMARKS_FIELD_NUMBER = 2;
  private java.lang.Object remarks_;
  /**
   * <code>optional string remarks = 2;</code>
   */
  public boolean hasRemarks() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional string remarks = 2;</code>
   */
  public java.lang.String getRemarks() {
    java.lang.Object ref = remarks_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        remarks_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string remarks = 2;</code>
   */
  public com.google.protobuf.ByteString
      getRemarksBytes() {
    java.lang.Object ref = remarks_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      remarks_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ACCNO_FIELD_NUMBER = 3;
  private java.lang.Object accno_;
  /**
   * <code>optional string accno = 3;</code>
   */
  public boolean hasAccno() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional string accno = 3;</code>
   */
  public java.lang.String getAccno() {
    java.lang.Object ref = accno_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        accno_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string accno = 3;</code>
   */
  public com.google.protobuf.ByteString
      getAccnoBytes() {
    java.lang.Object ref = accno_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      accno_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MODIFYCHECKOVERDUEDATA_FIELD_NUMBER = 4;
  private com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueData modifyCheckOverdueData_;
  /**
   * <code>optional .com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueData modifyCheckOverdueData = 4;</code>
   */
  public boolean hasModifyCheckOverdueData() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>optional .com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueData modifyCheckOverdueData = 4;</code>
   */
  public com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueData getModifyCheckOverdueData() {
    return modifyCheckOverdueData_;
  }
  /**
   * <code>optional .com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueData modifyCheckOverdueData = 4;</code>
   */
  public com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueDataOrBuilder getModifyCheckOverdueDataOrBuilder() {
    return modifyCheckOverdueData_;
  }

  private void initFields() {
    status_ = 0;
    remarks_ = "";
    accno_ = "";
    modifyCheckOverdueData_ = com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueData.getDefaultInstance();
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasStatus()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeUInt32(1, status_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeBytes(2, getRemarksBytes());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeBytes(3, getAccnoBytes());
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeMessage(4, modifyCheckOverdueData_);
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, status_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, getRemarksBytes());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, getAccnoBytes());
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, modifyCheckOverdueData_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueResponse prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueResponse)
      com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bcasekuritas.rabbitmq.proto.bcas.Bcasolt.internal_static_com_bcasekuritas_rabbitmq_proto_bcas_ModifyCheckOverdueResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bcasekuritas.rabbitmq.proto.bcas.Bcasolt.internal_static_com_bcasekuritas_rabbitmq_proto_bcas_ModifyCheckOverdueResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueResponse.class, com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueResponse.Builder.class);
    }

    // Construct using com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getModifyCheckOverdueDataFieldBuilder();
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      status_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      remarks_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      accno_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      if (modifyCheckOverdueDataBuilder_ == null) {
        modifyCheckOverdueData_ = com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueData.getDefaultInstance();
      } else {
        modifyCheckOverdueDataBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bcasekuritas.rabbitmq.proto.bcas.Bcasolt.internal_static_com_bcasekuritas_rabbitmq_proto_bcas_ModifyCheckOverdueResponse_descriptor;
    }

    public com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueResponse getDefaultInstanceForType() {
      return com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueResponse.getDefaultInstance();
    }

    public com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueResponse build() {
      com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueResponse buildPartial() {
      com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueResponse result = new com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.status_ = status_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.remarks_ = remarks_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.accno_ = accno_;
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000008;
      }
      if (modifyCheckOverdueDataBuilder_ == null) {
        result.modifyCheckOverdueData_ = modifyCheckOverdueData_;
      } else {
        result.modifyCheckOverdueData_ = modifyCheckOverdueDataBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueResponse) {
        return mergeFrom((com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueResponse other) {
      if (other == com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueResponse.getDefaultInstance()) return this;
      if (other.hasStatus()) {
        setStatus(other.getStatus());
      }
      if (other.hasRemarks()) {
        bitField0_ |= 0x00000002;
        remarks_ = other.remarks_;
        onChanged();
      }
      if (other.hasAccno()) {
        bitField0_ |= 0x00000004;
        accno_ = other.accno_;
        onChanged();
      }
      if (other.hasModifyCheckOverdueData()) {
        mergeModifyCheckOverdueData(other.getModifyCheckOverdueData());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasStatus()) {
        
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueResponse) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int status_ ;
    /**
     * <code>required uint32 status = 1;</code>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 status = 1;</code>
     */
    public int getStatus() {
      return status_;
    }
    /**
     * <code>required uint32 status = 1;</code>
     */
    public Builder setStatus(int value) {
      bitField0_ |= 0x00000001;
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required uint32 status = 1;</code>
     */
    public Builder clearStatus() {
      bitField0_ = (bitField0_ & ~0x00000001);
      status_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object remarks_ = "";
    /**
     * <code>optional string remarks = 2;</code>
     */
    public boolean hasRemarks() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string remarks = 2;</code>
     */
    public java.lang.String getRemarks() {
      java.lang.Object ref = remarks_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          remarks_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string remarks = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRemarksBytes() {
      java.lang.Object ref = remarks_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        remarks_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string remarks = 2;</code>
     */
    public Builder setRemarks(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      remarks_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string remarks = 2;</code>
     */
    public Builder clearRemarks() {
      bitField0_ = (bitField0_ & ~0x00000002);
      remarks_ = getDefaultInstance().getRemarks();
      onChanged();
      return this;
    }
    /**
     * <code>optional string remarks = 2;</code>
     */
    public Builder setRemarksBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      remarks_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object accno_ = "";
    /**
     * <code>optional string accno = 3;</code>
     */
    public boolean hasAccno() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string accno = 3;</code>
     */
    public java.lang.String getAccno() {
      java.lang.Object ref = accno_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          accno_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string accno = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAccnoBytes() {
      java.lang.Object ref = accno_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accno_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string accno = 3;</code>
     */
    public Builder setAccno(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      accno_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string accno = 3;</code>
     */
    public Builder clearAccno() {
      bitField0_ = (bitField0_ & ~0x00000004);
      accno_ = getDefaultInstance().getAccno();
      onChanged();
      return this;
    }
    /**
     * <code>optional string accno = 3;</code>
     */
    public Builder setAccnoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      accno_ = value;
      onChanged();
      return this;
    }

    private com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueData modifyCheckOverdueData_ = com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueData.getDefaultInstance();
    private com.google.protobuf.SingleFieldBuilder<
        com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueData, com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueData.Builder, com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueDataOrBuilder> modifyCheckOverdueDataBuilder_;
    /**
     * <code>optional .com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueData modifyCheckOverdueData = 4;</code>
     */
    public boolean hasModifyCheckOverdueData() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueData modifyCheckOverdueData = 4;</code>
     */
    public com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueData getModifyCheckOverdueData() {
      if (modifyCheckOverdueDataBuilder_ == null) {
        return modifyCheckOverdueData_;
      } else {
        return modifyCheckOverdueDataBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueData modifyCheckOverdueData = 4;</code>
     */
    public Builder setModifyCheckOverdueData(com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueData value) {
      if (modifyCheckOverdueDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        modifyCheckOverdueData_ = value;
        onChanged();
      } else {
        modifyCheckOverdueDataBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      return this;
    }
    /**
     * <code>optional .com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueData modifyCheckOverdueData = 4;</code>
     */
    public Builder setModifyCheckOverdueData(
        com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueData.Builder builderForValue) {
      if (modifyCheckOverdueDataBuilder_ == null) {
        modifyCheckOverdueData_ = builderForValue.build();
        onChanged();
      } else {
        modifyCheckOverdueDataBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      return this;
    }
    /**
     * <code>optional .com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueData modifyCheckOverdueData = 4;</code>
     */
    public Builder mergeModifyCheckOverdueData(com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueData value) {
      if (modifyCheckOverdueDataBuilder_ == null) {
        if (((bitField0_ & 0x00000008) == 0x00000008) &&
            modifyCheckOverdueData_ != com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueData.getDefaultInstance()) {
          modifyCheckOverdueData_ =
            com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueData.newBuilder(modifyCheckOverdueData_).mergeFrom(value).buildPartial();
        } else {
          modifyCheckOverdueData_ = value;
        }
        onChanged();
      } else {
        modifyCheckOverdueDataBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000008;
      return this;
    }
    /**
     * <code>optional .com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueData modifyCheckOverdueData = 4;</code>
     */
    public Builder clearModifyCheckOverdueData() {
      if (modifyCheckOverdueDataBuilder_ == null) {
        modifyCheckOverdueData_ = com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueData.getDefaultInstance();
        onChanged();
      } else {
        modifyCheckOverdueDataBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }
    /**
     * <code>optional .com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueData modifyCheckOverdueData = 4;</code>
     */
    public com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueData.Builder getModifyCheckOverdueDataBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getModifyCheckOverdueDataFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueData modifyCheckOverdueData = 4;</code>
     */
    public com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueDataOrBuilder getModifyCheckOverdueDataOrBuilder() {
      if (modifyCheckOverdueDataBuilder_ != null) {
        return modifyCheckOverdueDataBuilder_.getMessageOrBuilder();
      } else {
        return modifyCheckOverdueData_;
      }
    }
    /**
     * <code>optional .com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueData modifyCheckOverdueData = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueData, com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueData.Builder, com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueDataOrBuilder> 
        getModifyCheckOverdueDataFieldBuilder() {
      if (modifyCheckOverdueDataBuilder_ == null) {
        modifyCheckOverdueDataBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueData, com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueData.Builder, com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueDataOrBuilder>(
                getModifyCheckOverdueData(),
                getParentForChildren(),
                isClean());
        modifyCheckOverdueData_ = null;
      }
      return modifyCheckOverdueDataBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueResponse)
  }

  static {
    defaultInstance = new ModifyCheckOverdueResponse(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:com.bcasekuritas.rabbitmq.proto.bcas.ModifyCheckOverdueResponse)
}

