// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Bcasolt.proto

package com.bcasekuritas.rabbitmq.proto.bcas;

public interface RealizeGainLossRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.bcasekuritas.rabbitmq.proto.bcas.RealizeGainLossRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string userId = 1;</code>
   */
  boolean hasUserId();
  /**
   * <code>required string userId = 1;</code>
   */
  java.lang.String getUserId();
  /**
   * <code>required string userId = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>optional string accNo = 2;</code>
   */
  boolean hasAccNo();
  /**
   * <code>optional string accNo = 2;</code>
   */
  java.lang.String getAccNo();
  /**
   * <code>optional string accNo = 2;</code>
   */
  com.google.protobuf.ByteString
      getAccNoBytes();

  /**
   * <code>optional uint32 month = 3;</code>
   */
  boolean hasMonth();
  /**
   * <code>optional uint32 month = 3;</code>
   */
  int getMonth();

  /**
   * <code>optional uint32 year = 4;</code>
   */
  boolean hasYear();
  /**
   * <code>optional uint32 year = 4;</code>
   */
  int getYear();

  /**
   * <code>optional string sessionId = 5;</code>
   */
  boolean hasSessionId();
  /**
   * <code>optional string sessionId = 5;</code>
   */
  java.lang.String getSessionId();
  /**
   * <code>optional string sessionId = 5;</code>
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();
}
