// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Bcasolt.proto

package com.bcasekuritas.rabbitmq.proto.bcas;

public interface RealizeGainLossResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.bcasekuritas.rabbitmq.proto.bcas.RealizeGainLossResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required uint32 status = 1;</code>
   */
  boolean hasStatus();
  /**
   * <code>required uint32 status = 1;</code>
   */
  int getStatus();

  /**
   * <code>optional string remarks = 2;</code>
   */
  boolean hasRemarks();
  /**
   * <code>optional string remarks = 2;</code>
   */
  java.lang.String getRemarks();
  /**
   * <code>optional string remarks = 2;</code>
   */
  com.google.protobuf.ByteString
      getRemarksBytes();

  /**
   * <code>repeated .com.bcasekuritas.rabbitmq.proto.bcas.RealizeGainLoss realizeGainLossInfo = 3;</code>
   */
  java.util.List<com.bcasekuritas.rabbitmq.proto.bcas.RealizeGainLoss> 
      getRealizeGainLossInfoList();
  /**
   * <code>repeated .com.bcasekuritas.rabbitmq.proto.bcas.RealizeGainLoss realizeGainLossInfo = 3;</code>
   */
  com.bcasekuritas.rabbitmq.proto.bcas.RealizeGainLoss getRealizeGainLossInfo(int index);
  /**
   * <code>repeated .com.bcasekuritas.rabbitmq.proto.bcas.RealizeGainLoss realizeGainLossInfo = 3;</code>
   */
  int getRealizeGainLossInfoCount();
  /**
   * <code>repeated .com.bcasekuritas.rabbitmq.proto.bcas.RealizeGainLoss realizeGainLossInfo = 3;</code>
   */
  java.util.List<? extends com.bcasekuritas.rabbitmq.proto.bcas.RealizeGainLossOrBuilder> 
      getRealizeGainLossInfoOrBuilderList();
  /**
   * <code>repeated .com.bcasekuritas.rabbitmq.proto.bcas.RealizeGainLoss realizeGainLossInfo = 3;</code>
   */
  com.bcasekuritas.rabbitmq.proto.bcas.RealizeGainLossOrBuilder getRealizeGainLossInfoOrBuilder(
      int index);
}
