// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Bcasolt.proto

package com.bcasekuritas.rabbitmq.proto.bcas;

public interface StatementOfAccountResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.bcasekuritas.rabbitmq.proto.bcas.StatementOfAccountResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required uint32 status = 1;</code>
   */
  boolean hasStatus();
  /**
   * <code>required uint32 status = 1;</code>
   */
  int getStatus();

  /**
   * <code>optional string remarks = 2;</code>
   */
  boolean hasRemarks();
  /**
   * <code>optional string remarks = 2;</code>
   */
  java.lang.String getRemarks();
  /**
   * <code>optional string remarks = 2;</code>
   */
  com.google.protobuf.ByteString
      getRemarksBytes();

  /**
   * <code>repeated .com.bcasekuritas.rabbitmq.proto.bcas.StatementOfAccountInfo statementOfAccountInfo = 3;</code>
   */
  java.util.List<com.bcasekuritas.rabbitmq.proto.bcas.StatementOfAccountInfo> 
      getStatementOfAccountInfoList();
  /**
   * <code>repeated .com.bcasekuritas.rabbitmq.proto.bcas.StatementOfAccountInfo statementOfAccountInfo = 3;</code>
   */
  com.bcasekuritas.rabbitmq.proto.bcas.StatementOfAccountInfo getStatementOfAccountInfo(int index);
  /**
   * <code>repeated .com.bcasekuritas.rabbitmq.proto.bcas.StatementOfAccountInfo statementOfAccountInfo = 3;</code>
   */
  int getStatementOfAccountInfoCount();
  /**
   * <code>repeated .com.bcasekuritas.rabbitmq.proto.bcas.StatementOfAccountInfo statementOfAccountInfo = 3;</code>
   */
  java.util.List<? extends com.bcasekuritas.rabbitmq.proto.bcas.StatementOfAccountInfoOrBuilder> 
      getStatementOfAccountInfoOrBuilderList();
  /**
   * <code>repeated .com.bcasekuritas.rabbitmq.proto.bcas.StatementOfAccountInfo statementOfAccountInfo = 3;</code>
   */
  com.bcasekuritas.rabbitmq.proto.bcas.StatementOfAccountInfoOrBuilder getStatementOfAccountInfoOrBuilder(
      int index);
}
