// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Bcasolt.proto

package com.bcasekuritas.rabbitmq.proto.bcas;

public interface StockTradeInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.bcasekuritas.rabbitmq.proto.bcas.StockTradeInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string stockcode = 1;</code>
   */
  boolean hasStockcode();
  /**
   * <code>required string stockcode = 1;</code>
   */
  java.lang.String getStockcode();
  /**
   * <code>required string stockcode = 1;</code>
   */
  com.google.protobuf.ByteString
      getStockcodeBytes();

  /**
   * <code>optional string boardcode = 2;</code>
   */
  boolean hasBoardcode();
  /**
   * <code>optional string boardcode = 2;</code>
   */
  java.lang.String getBoardcode();
  /**
   * <code>optional string boardcode = 2;</code>
   */
  com.google.protobuf.ByteString
      getBoardcodeBytes();

  /**
   * <code>optional string stockname = 3;</code>
   */
  boolean hasStockname();
  /**
   * <code>optional string stockname = 3;</code>
   */
  java.lang.String getStockname();
  /**
   * <code>optional string stockname = 3;</code>
   */
  com.google.protobuf.ByteString
      getStocknameBytes();

  /**
   * <code>optional string mktid = 4;</code>
   */
  boolean hasMktid();
  /**
   * <code>optional string mktid = 4;</code>
   */
  java.lang.String getMktid();
  /**
   * <code>optional string mktid = 4;</code>
   */
  com.google.protobuf.ByteString
      getMktidBytes();

  /**
   * <code>optional string tradePreop = 5;</code>
   */
  boolean hasTradePreop();
  /**
   * <code>optional string tradePreop = 5;</code>
   */
  java.lang.String getTradePreop();
  /**
   * <code>optional string tradePreop = 5;</code>
   */
  com.google.protobuf.ByteString
      getTradePreopBytes();

  /**
   * <code>optional int64 listingdate = 6;</code>
   */
  boolean hasListingdate();
  /**
   * <code>optional int64 listingdate = 6;</code>
   */
  long getListingdate();

  /**
   * <code>optional string status = 7;</code>
   */
  boolean hasStatus();
  /**
   * <code>optional string status = 7;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>optional string status = 7;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>optional uint32 lotsize = 8;</code>
   */
  boolean hasLotsize();
  /**
   * <code>optional uint32 lotsize = 8;</code>
   */
  int getLotsize();
}
