// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Bcasolt.proto

package com.bcasekuritas.rabbitmq.proto.bcas;

/**
 * Protobuf type {@code com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashRejectRequest}
 *
 * <pre>
 *API to request Reject Withdraw Cash
 *Queue Name      : cakra.withdraw_cash_reject_request-rpc
 *Class Request   : WithdrawCashRejectRequest
 *Class Response  : WithdrawCashRejectResponse
 * </pre>
 */
public final class WithdrawCashRejectRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashRejectRequest)
    WithdrawCashRejectRequestOrBuilder {
  // Use WithdrawCashRejectRequest.newBuilder() to construct.
  private WithdrawCashRejectRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private WithdrawCashRejectRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final WithdrawCashRejectRequest defaultInstance;
  public static WithdrawCashRejectRequest getDefaultInstance() {
    return defaultInstance;
  }

  public WithdrawCashRejectRequest getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private WithdrawCashRejectRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000001;
            userId_ = bs;
            break;
          }
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000002;
            sessionId_ = bs;
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              withdrawCashReject_ = new java.util.ArrayList<com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashReject>();
              mutable_bitField0_ |= 0x00000004;
            }
            withdrawCashReject_.add(input.readMessage(com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashReject.PARSER, extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        withdrawCashReject_ = java.util.Collections.unmodifiableList(withdrawCashReject_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bcasekuritas.rabbitmq.proto.bcas.Bcasolt.internal_static_com_bcasekuritas_rabbitmq_proto_bcas_WithdrawCashRejectRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bcasekuritas.rabbitmq.proto.bcas.Bcasolt.internal_static_com_bcasekuritas_rabbitmq_proto_bcas_WithdrawCashRejectRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashRejectRequest.class, com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashRejectRequest.Builder.class);
  }

  public static com.google.protobuf.Parser<WithdrawCashRejectRequest> PARSER =
      new com.google.protobuf.AbstractParser<WithdrawCashRejectRequest>() {
    public WithdrawCashRejectRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new WithdrawCashRejectRequest(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<WithdrawCashRejectRequest> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  public static final int USERID_FIELD_NUMBER = 1;
  private java.lang.Object userId_;
  /**
   * <code>optional string userId = 1;</code>
   */
  public boolean hasUserId() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional string userId = 1;</code>
   */
  public java.lang.String getUserId() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        userId_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string userId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getUserIdBytes() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SESSIONID_FIELD_NUMBER = 2;
  private java.lang.Object sessionId_;
  /**
   * <code>optional string sessionId = 2;</code>
   */
  public boolean hasSessionId() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional string sessionId = 2;</code>
   */
  public java.lang.String getSessionId() {
    java.lang.Object ref = sessionId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        sessionId_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string sessionId = 2;</code>
   */
  public com.google.protobuf.ByteString
      getSessionIdBytes() {
    java.lang.Object ref = sessionId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sessionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int WITHDRAWCASHREJECT_FIELD_NUMBER = 3;
  private java.util.List<com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashReject> withdrawCashReject_;
  /**
   * <code>repeated .com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashReject withdrawCashReject = 3;</code>
   */
  public java.util.List<com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashReject> getWithdrawCashRejectList() {
    return withdrawCashReject_;
  }
  /**
   * <code>repeated .com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashReject withdrawCashReject = 3;</code>
   */
  public java.util.List<? extends com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashRejectOrBuilder> 
      getWithdrawCashRejectOrBuilderList() {
    return withdrawCashReject_;
  }
  /**
   * <code>repeated .com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashReject withdrawCashReject = 3;</code>
   */
  public int getWithdrawCashRejectCount() {
    return withdrawCashReject_.size();
  }
  /**
   * <code>repeated .com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashReject withdrawCashReject = 3;</code>
   */
  public com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashReject getWithdrawCashReject(int index) {
    return withdrawCashReject_.get(index);
  }
  /**
   * <code>repeated .com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashReject withdrawCashReject = 3;</code>
   */
  public com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashRejectOrBuilder getWithdrawCashRejectOrBuilder(
      int index) {
    return withdrawCashReject_.get(index);
  }

  private void initFields() {
    userId_ = "";
    sessionId_ = "";
    withdrawCashReject_ = java.util.Collections.emptyList();
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeBytes(1, getUserIdBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeBytes(2, getSessionIdBytes());
    }
    for (int i = 0; i < withdrawCashReject_.size(); i++) {
      output.writeMessage(3, withdrawCashReject_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, getUserIdBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, getSessionIdBytes());
    }
    for (int i = 0; i < withdrawCashReject_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, withdrawCashReject_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashRejectRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashRejectRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashRejectRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashRejectRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashRejectRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashRejectRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashRejectRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashRejectRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashRejectRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashRejectRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashRejectRequest prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashRejectRequest}
   *
   * <pre>
   *API to request Reject Withdraw Cash
   *Queue Name      : cakra.withdraw_cash_reject_request-rpc
   *Class Request   : WithdrawCashRejectRequest
   *Class Response  : WithdrawCashRejectResponse
   * </pre>
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashRejectRequest)
      com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashRejectRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bcasekuritas.rabbitmq.proto.bcas.Bcasolt.internal_static_com_bcasekuritas_rabbitmq_proto_bcas_WithdrawCashRejectRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bcasekuritas.rabbitmq.proto.bcas.Bcasolt.internal_static_com_bcasekuritas_rabbitmq_proto_bcas_WithdrawCashRejectRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashRejectRequest.class, com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashRejectRequest.Builder.class);
    }

    // Construct using com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashRejectRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getWithdrawCashRejectFieldBuilder();
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      userId_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      sessionId_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      if (withdrawCashRejectBuilder_ == null) {
        withdrawCashReject_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        withdrawCashRejectBuilder_.clear();
      }
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bcasekuritas.rabbitmq.proto.bcas.Bcasolt.internal_static_com_bcasekuritas_rabbitmq_proto_bcas_WithdrawCashRejectRequest_descriptor;
    }

    public com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashRejectRequest getDefaultInstanceForType() {
      return com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashRejectRequest.getDefaultInstance();
    }

    public com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashRejectRequest build() {
      com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashRejectRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashRejectRequest buildPartial() {
      com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashRejectRequest result = new com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashRejectRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.userId_ = userId_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.sessionId_ = sessionId_;
      if (withdrawCashRejectBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          withdrawCashReject_ = java.util.Collections.unmodifiableList(withdrawCashReject_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.withdrawCashReject_ = withdrawCashReject_;
      } else {
        result.withdrawCashReject_ = withdrawCashRejectBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashRejectRequest) {
        return mergeFrom((com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashRejectRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashRejectRequest other) {
      if (other == com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashRejectRequest.getDefaultInstance()) return this;
      if (other.hasUserId()) {
        bitField0_ |= 0x00000001;
        userId_ = other.userId_;
        onChanged();
      }
      if (other.hasSessionId()) {
        bitField0_ |= 0x00000002;
        sessionId_ = other.sessionId_;
        onChanged();
      }
      if (withdrawCashRejectBuilder_ == null) {
        if (!other.withdrawCashReject_.isEmpty()) {
          if (withdrawCashReject_.isEmpty()) {
            withdrawCashReject_ = other.withdrawCashReject_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureWithdrawCashRejectIsMutable();
            withdrawCashReject_.addAll(other.withdrawCashReject_);
          }
          onChanged();
        }
      } else {
        if (!other.withdrawCashReject_.isEmpty()) {
          if (withdrawCashRejectBuilder_.isEmpty()) {
            withdrawCashRejectBuilder_.dispose();
            withdrawCashRejectBuilder_ = null;
            withdrawCashReject_ = other.withdrawCashReject_;
            bitField0_ = (bitField0_ & ~0x00000004);
            withdrawCashRejectBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getWithdrawCashRejectFieldBuilder() : null;
          } else {
            withdrawCashRejectBuilder_.addAllMessages(other.withdrawCashReject_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashRejectRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashRejectRequest) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object userId_ = "";
    /**
     * <code>optional string userId = 1;</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string userId = 1;</code>
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userId_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string userId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string userId = 1;</code>
     */
    public Builder setUserId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      userId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string userId = 1;</code>
     */
    public Builder clearUserId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      userId_ = getDefaultInstance().getUserId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string userId = 1;</code>
     */
    public Builder setUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      userId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object sessionId_ = "";
    /**
     * <code>optional string sessionId = 2;</code>
     */
    public boolean hasSessionId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string sessionId = 2;</code>
     */
    public java.lang.String getSessionId() {
      java.lang.Object ref = sessionId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sessionId_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string sessionId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSessionIdBytes() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string sessionId = 2;</code>
     */
    public Builder setSessionId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      sessionId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string sessionId = 2;</code>
     */
    public Builder clearSessionId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      sessionId_ = getDefaultInstance().getSessionId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string sessionId = 2;</code>
     */
    public Builder setSessionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      sessionId_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashReject> withdrawCashReject_ =
      java.util.Collections.emptyList();
    private void ensureWithdrawCashRejectIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        withdrawCashReject_ = new java.util.ArrayList<com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashReject>(withdrawCashReject_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashReject, com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashReject.Builder, com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashRejectOrBuilder> withdrawCashRejectBuilder_;

    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashReject withdrawCashReject = 3;</code>
     */
    public java.util.List<com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashReject> getWithdrawCashRejectList() {
      if (withdrawCashRejectBuilder_ == null) {
        return java.util.Collections.unmodifiableList(withdrawCashReject_);
      } else {
        return withdrawCashRejectBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashReject withdrawCashReject = 3;</code>
     */
    public int getWithdrawCashRejectCount() {
      if (withdrawCashRejectBuilder_ == null) {
        return withdrawCashReject_.size();
      } else {
        return withdrawCashRejectBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashReject withdrawCashReject = 3;</code>
     */
    public com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashReject getWithdrawCashReject(int index) {
      if (withdrawCashRejectBuilder_ == null) {
        return withdrawCashReject_.get(index);
      } else {
        return withdrawCashRejectBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashReject withdrawCashReject = 3;</code>
     */
    public Builder setWithdrawCashReject(
        int index, com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashReject value) {
      if (withdrawCashRejectBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureWithdrawCashRejectIsMutable();
        withdrawCashReject_.set(index, value);
        onChanged();
      } else {
        withdrawCashRejectBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashReject withdrawCashReject = 3;</code>
     */
    public Builder setWithdrawCashReject(
        int index, com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashReject.Builder builderForValue) {
      if (withdrawCashRejectBuilder_ == null) {
        ensureWithdrawCashRejectIsMutable();
        withdrawCashReject_.set(index, builderForValue.build());
        onChanged();
      } else {
        withdrawCashRejectBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashReject withdrawCashReject = 3;</code>
     */
    public Builder addWithdrawCashReject(com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashReject value) {
      if (withdrawCashRejectBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureWithdrawCashRejectIsMutable();
        withdrawCashReject_.add(value);
        onChanged();
      } else {
        withdrawCashRejectBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashReject withdrawCashReject = 3;</code>
     */
    public Builder addWithdrawCashReject(
        int index, com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashReject value) {
      if (withdrawCashRejectBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureWithdrawCashRejectIsMutable();
        withdrawCashReject_.add(index, value);
        onChanged();
      } else {
        withdrawCashRejectBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashReject withdrawCashReject = 3;</code>
     */
    public Builder addWithdrawCashReject(
        com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashReject.Builder builderForValue) {
      if (withdrawCashRejectBuilder_ == null) {
        ensureWithdrawCashRejectIsMutable();
        withdrawCashReject_.add(builderForValue.build());
        onChanged();
      } else {
        withdrawCashRejectBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashReject withdrawCashReject = 3;</code>
     */
    public Builder addWithdrawCashReject(
        int index, com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashReject.Builder builderForValue) {
      if (withdrawCashRejectBuilder_ == null) {
        ensureWithdrawCashRejectIsMutable();
        withdrawCashReject_.add(index, builderForValue.build());
        onChanged();
      } else {
        withdrawCashRejectBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashReject withdrawCashReject = 3;</code>
     */
    public Builder addAllWithdrawCashReject(
        java.lang.Iterable<? extends com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashReject> values) {
      if (withdrawCashRejectBuilder_ == null) {
        ensureWithdrawCashRejectIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, withdrawCashReject_);
        onChanged();
      } else {
        withdrawCashRejectBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashReject withdrawCashReject = 3;</code>
     */
    public Builder clearWithdrawCashReject() {
      if (withdrawCashRejectBuilder_ == null) {
        withdrawCashReject_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        withdrawCashRejectBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashReject withdrawCashReject = 3;</code>
     */
    public Builder removeWithdrawCashReject(int index) {
      if (withdrawCashRejectBuilder_ == null) {
        ensureWithdrawCashRejectIsMutable();
        withdrawCashReject_.remove(index);
        onChanged();
      } else {
        withdrawCashRejectBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashReject withdrawCashReject = 3;</code>
     */
    public com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashReject.Builder getWithdrawCashRejectBuilder(
        int index) {
      return getWithdrawCashRejectFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashReject withdrawCashReject = 3;</code>
     */
    public com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashRejectOrBuilder getWithdrawCashRejectOrBuilder(
        int index) {
      if (withdrawCashRejectBuilder_ == null) {
        return withdrawCashReject_.get(index);  } else {
        return withdrawCashRejectBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashReject withdrawCashReject = 3;</code>
     */
    public java.util.List<? extends com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashRejectOrBuilder> 
         getWithdrawCashRejectOrBuilderList() {
      if (withdrawCashRejectBuilder_ != null) {
        return withdrawCashRejectBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(withdrawCashReject_);
      }
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashReject withdrawCashReject = 3;</code>
     */
    public com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashReject.Builder addWithdrawCashRejectBuilder() {
      return getWithdrawCashRejectFieldBuilder().addBuilder(
          com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashReject.getDefaultInstance());
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashReject withdrawCashReject = 3;</code>
     */
    public com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashReject.Builder addWithdrawCashRejectBuilder(
        int index) {
      return getWithdrawCashRejectFieldBuilder().addBuilder(
          index, com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashReject.getDefaultInstance());
    }
    /**
     * <code>repeated .com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashReject withdrawCashReject = 3;</code>
     */
    public java.util.List<com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashReject.Builder> 
         getWithdrawCashRejectBuilderList() {
      return getWithdrawCashRejectFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashReject, com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashReject.Builder, com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashRejectOrBuilder> 
        getWithdrawCashRejectFieldBuilder() {
      if (withdrawCashRejectBuilder_ == null) {
        withdrawCashRejectBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashReject, com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashReject.Builder, com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashRejectOrBuilder>(
                withdrawCashReject_,
                ((bitField0_ & 0x00000004) == 0x00000004),
                getParentForChildren(),
                isClean());
        withdrawCashReject_ = null;
      }
      return withdrawCashRejectBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashRejectRequest)
  }

  static {
    defaultInstance = new WithdrawCashRejectRequest(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:com.bcasekuritas.rabbitmq.proto.bcas.WithdrawCashRejectRequest)
}

