// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bcasdfdictionary.proto

package com.bcasekuritas.rabbitmq.proto.datafeed;

public interface IntervalPriceInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.bcasekuritas.rabbitmq.proto.datafeed.IntervalPriceInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required uint64 axisDate = 1;</code>
   *
   * <pre>
   * x-axis graph
   * </pre>
   */
  boolean hasAxisDate();
  /**
   * <code>required uint64 axisDate = 1;</code>
   *
   * <pre>
   * x-axis graph
   * </pre>
   */
  long getAxisDate();

  /**
   * <code>required string axisLabel = 2;</code>
   *
   * <pre>
   * x-axis graph
   * </pre>
   */
  boolean hasAxisLabel();
  /**
   * <code>required string axisLabel = 2;</code>
   *
   * <pre>
   * x-axis graph
   * </pre>
   */
  java.lang.String getAxisLabel();
  /**
   * <code>required string axisLabel = 2;</code>
   *
   * <pre>
   * x-axis graph
   * </pre>
   */
  com.google.protobuf.ByteString
      getAxisLabelBytes();

  /**
   * <code>required double price = 3;</code>
   */
  boolean hasPrice();
  /**
   * <code>required double price = 3;</code>
   */
  double getPrice();

  /**
   * <code>required double prev = 4;</code>
   */
  boolean hasPrev();
  /**
   * <code>required double prev = 4;</code>
   */
  double getPrev();

  /**
   * <code>required double open = 5;</code>
   */
  boolean hasOpen();
  /**
   * <code>required double open = 5;</code>
   */
  double getOpen();

  /**
   * <code>required double high = 6;</code>
   */
  boolean hasHigh();
  /**
   * <code>required double high = 6;</code>
   */
  double getHigh();

  /**
   * <code>required double low = 7;</code>
   *
   * <pre>
   *required int32  seqNo 		= 7;
   * </pre>
   */
  boolean hasLow();
  /**
   * <code>required double low = 7;</code>
   *
   * <pre>
   *required int32  seqNo 		= 7;
   * </pre>
   */
  double getLow();
}
