// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bcasdfdictionary.proto

package com.bcasekuritas.rabbitmq.proto.datafeed;

public interface IntervalIndiceResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.bcasekuritas.rabbitmq.proto.datafeed.IntervalIndiceResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required uint32 status = 1;</code>
   *
   * <pre>
   * 0=OK, 1=error, 2=invalid session or expired
   * </pre>
   */
  boolean hasStatus();
  /**
   * <code>required uint32 status = 1;</code>
   *
   * <pre>
   * 0=OK, 1=error, 2=invalid session or expired
   * </pre>
   */
  int getStatus();

  /**
   * <code>optional string remarks = 2;</code>
   */
  boolean hasRemarks();
  /**
   * <code>optional string remarks = 2;</code>
   */
  java.lang.String getRemarks();
  /**
   * <code>optional string remarks = 2;</code>
   */
  com.google.protobuf.ByteString
      getRemarksBytes();

  /**
   * <code>required int32 interval = 3;</code>
   *
   * <pre>
   * 1=weekly, 2=1M, 3=3M, 4=1Y, 5=3Y, 6=5Y, 7=YTD
   * </pre>
   */
  boolean hasInterval();
  /**
   * <code>required int32 interval = 3;</code>
   *
   * <pre>
   * 1=weekly, 2=1M, 3=3M, 4=1Y, 5=3Y, 6=5Y, 7=YTD
   * </pre>
   */
  int getInterval();

  /**
   * <code>required string itemCode = 4;</code>
   *
   * <pre>
   * indice/stock, stock -&gt; boardcode required
   * </pre>
   */
  boolean hasItemCode();
  /**
   * <code>required string itemCode = 4;</code>
   *
   * <pre>
   * indice/stock, stock -&gt; boardcode required
   * </pre>
   */
  java.lang.String getItemCode();
  /**
   * <code>required string itemCode = 4;</code>
   *
   * <pre>
   * indice/stock, stock -&gt; boardcode required
   * </pre>
   */
  com.google.protobuf.ByteString
      getItemCodeBytes();

  /**
   * <code>repeated .com.bcasekuritas.rabbitmq.proto.datafeed.IntervalIndiceInfo indiceInfo = 5;</code>
   */
  java.util.List<com.bcasekuritas.rabbitmq.proto.datafeed.IntervalIndiceInfo> 
      getIndiceInfoList();
  /**
   * <code>repeated .com.bcasekuritas.rabbitmq.proto.datafeed.IntervalIndiceInfo indiceInfo = 5;</code>
   */
  com.bcasekuritas.rabbitmq.proto.datafeed.IntervalIndiceInfo getIndiceInfo(int index);
  /**
   * <code>repeated .com.bcasekuritas.rabbitmq.proto.datafeed.IntervalIndiceInfo indiceInfo = 5;</code>
   */
  int getIndiceInfoCount();
  /**
   * <code>repeated .com.bcasekuritas.rabbitmq.proto.datafeed.IntervalIndiceInfo indiceInfo = 5;</code>
   */
  java.util.List<? extends com.bcasekuritas.rabbitmq.proto.datafeed.IntervalIndiceInfoOrBuilder> 
      getIndiceInfoOrBuilderList();
  /**
   * <code>repeated .com.bcasekuritas.rabbitmq.proto.datafeed.IntervalIndiceInfo indiceInfo = 5;</code>
   */
  com.bcasekuritas.rabbitmq.proto.datafeed.IntervalIndiceInfoOrBuilder getIndiceInfoOrBuilder(
      int index);
}
