// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bcasdfdictionary.proto

package com.bcasekuritas.rabbitmq.proto.datafeed;

/**
 * Protobuf type {@code com.bcasekuritas.rabbitmq.proto.datafeed.OrderData}
 */
public final class OrderData extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.bcasekuritas.rabbitmq.proto.datafeed.OrderData)
    OrderDataOrBuilder {
  // Use OrderData.newBuilder() to construct.
  private OrderData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private OrderData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final OrderData defaultInstance;
  public static OrderData getDefaultInstance() {
    return defaultInstance;
  }

  public OrderData getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private OrderData(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000001;
            boardCode_ = bs;
            break;
          }
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000002;
            secCode_ = bs;
            break;
          }
          case 26: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000004;
            data_ = bs;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bcasekuritas.rabbitmq.proto.datafeed.Bcasdfdictionary.internal_static_com_bcasekuritas_rabbitmq_proto_datafeed_OrderData_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bcasekuritas.rabbitmq.proto.datafeed.Bcasdfdictionary.internal_static_com_bcasekuritas_rabbitmq_proto_datafeed_OrderData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bcasekuritas.rabbitmq.proto.datafeed.OrderData.class, com.bcasekuritas.rabbitmq.proto.datafeed.OrderData.Builder.class);
  }

  public static com.google.protobuf.Parser<OrderData> PARSER =
      new com.google.protobuf.AbstractParser<OrderData>() {
    public OrderData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new OrderData(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<OrderData> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  public static final int BOARDCODE_FIELD_NUMBER = 1;
  private java.lang.Object boardCode_;
  /**
   * <code>required string boardCode = 1;</code>
   */
  public boolean hasBoardCode() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required string boardCode = 1;</code>
   */
  public java.lang.String getBoardCode() {
    java.lang.Object ref = boardCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        boardCode_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string boardCode = 1;</code>
   */
  public com.google.protobuf.ByteString
      getBoardCodeBytes() {
    java.lang.Object ref = boardCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      boardCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SECCODE_FIELD_NUMBER = 2;
  private java.lang.Object secCode_;
  /**
   * <code>required string secCode = 2;</code>
   */
  public boolean hasSecCode() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>required string secCode = 2;</code>
   */
  public java.lang.String getSecCode() {
    java.lang.Object ref = secCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        secCode_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string secCode = 2;</code>
   */
  public com.google.protobuf.ByteString
      getSecCodeBytes() {
    java.lang.Object ref = secCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      secCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATA_FIELD_NUMBER = 3;
  private java.lang.Object data_;
  /**
   * <code>optional string data = 3;</code>
   */
  public boolean hasData() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional string data = 3;</code>
   */
  public java.lang.String getData() {
    java.lang.Object ref = data_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        data_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string data = 3;</code>
   */
  public com.google.protobuf.ByteString
      getDataBytes() {
    java.lang.Object ref = data_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      data_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private void initFields() {
    boardCode_ = "";
    secCode_ = "";
    data_ = "";
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasBoardCode()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasSecCode()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeBytes(1, getBoardCodeBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeBytes(2, getSecCodeBytes());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeBytes(3, getDataBytes());
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, getBoardCodeBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, getSecCodeBytes());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, getDataBytes());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static com.bcasekuritas.rabbitmq.proto.datafeed.OrderData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bcasekuritas.rabbitmq.proto.datafeed.OrderData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bcasekuritas.rabbitmq.proto.datafeed.OrderData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bcasekuritas.rabbitmq.proto.datafeed.OrderData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bcasekuritas.rabbitmq.proto.datafeed.OrderData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.bcasekuritas.rabbitmq.proto.datafeed.OrderData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.bcasekuritas.rabbitmq.proto.datafeed.OrderData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.bcasekuritas.rabbitmq.proto.datafeed.OrderData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.bcasekuritas.rabbitmq.proto.datafeed.OrderData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.bcasekuritas.rabbitmq.proto.datafeed.OrderData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.bcasekuritas.rabbitmq.proto.datafeed.OrderData prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.bcasekuritas.rabbitmq.proto.datafeed.OrderData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.bcasekuritas.rabbitmq.proto.datafeed.OrderData)
      com.bcasekuritas.rabbitmq.proto.datafeed.OrderDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bcasekuritas.rabbitmq.proto.datafeed.Bcasdfdictionary.internal_static_com_bcasekuritas_rabbitmq_proto_datafeed_OrderData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bcasekuritas.rabbitmq.proto.datafeed.Bcasdfdictionary.internal_static_com_bcasekuritas_rabbitmq_proto_datafeed_OrderData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bcasekuritas.rabbitmq.proto.datafeed.OrderData.class, com.bcasekuritas.rabbitmq.proto.datafeed.OrderData.Builder.class);
    }

    // Construct using com.bcasekuritas.rabbitmq.proto.datafeed.OrderData.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      boardCode_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      secCode_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      data_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bcasekuritas.rabbitmq.proto.datafeed.Bcasdfdictionary.internal_static_com_bcasekuritas_rabbitmq_proto_datafeed_OrderData_descriptor;
    }

    public com.bcasekuritas.rabbitmq.proto.datafeed.OrderData getDefaultInstanceForType() {
      return com.bcasekuritas.rabbitmq.proto.datafeed.OrderData.getDefaultInstance();
    }

    public com.bcasekuritas.rabbitmq.proto.datafeed.OrderData build() {
      com.bcasekuritas.rabbitmq.proto.datafeed.OrderData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.bcasekuritas.rabbitmq.proto.datafeed.OrderData buildPartial() {
      com.bcasekuritas.rabbitmq.proto.datafeed.OrderData result = new com.bcasekuritas.rabbitmq.proto.datafeed.OrderData(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.boardCode_ = boardCode_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.secCode_ = secCode_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.data_ = data_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bcasekuritas.rabbitmq.proto.datafeed.OrderData) {
        return mergeFrom((com.bcasekuritas.rabbitmq.proto.datafeed.OrderData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bcasekuritas.rabbitmq.proto.datafeed.OrderData other) {
      if (other == com.bcasekuritas.rabbitmq.proto.datafeed.OrderData.getDefaultInstance()) return this;
      if (other.hasBoardCode()) {
        bitField0_ |= 0x00000001;
        boardCode_ = other.boardCode_;
        onChanged();
      }
      if (other.hasSecCode()) {
        bitField0_ |= 0x00000002;
        secCode_ = other.secCode_;
        onChanged();
      }
      if (other.hasData()) {
        bitField0_ |= 0x00000004;
        data_ = other.data_;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasBoardCode()) {
        
        return false;
      }
      if (!hasSecCode()) {
        
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.bcasekuritas.rabbitmq.proto.datafeed.OrderData parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.bcasekuritas.rabbitmq.proto.datafeed.OrderData) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object boardCode_ = "";
    /**
     * <code>required string boardCode = 1;</code>
     */
    public boolean hasBoardCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string boardCode = 1;</code>
     */
    public java.lang.String getBoardCode() {
      java.lang.Object ref = boardCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          boardCode_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string boardCode = 1;</code>
     */
    public com.google.protobuf.ByteString
        getBoardCodeBytes() {
      java.lang.Object ref = boardCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        boardCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string boardCode = 1;</code>
     */
    public Builder setBoardCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      boardCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string boardCode = 1;</code>
     */
    public Builder clearBoardCode() {
      bitField0_ = (bitField0_ & ~0x00000001);
      boardCode_ = getDefaultInstance().getBoardCode();
      onChanged();
      return this;
    }
    /**
     * <code>required string boardCode = 1;</code>
     */
    public Builder setBoardCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      boardCode_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object secCode_ = "";
    /**
     * <code>required string secCode = 2;</code>
     */
    public boolean hasSecCode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string secCode = 2;</code>
     */
    public java.lang.String getSecCode() {
      java.lang.Object ref = secCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          secCode_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string secCode = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSecCodeBytes() {
      java.lang.Object ref = secCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        secCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string secCode = 2;</code>
     */
    public Builder setSecCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      secCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string secCode = 2;</code>
     */
    public Builder clearSecCode() {
      bitField0_ = (bitField0_ & ~0x00000002);
      secCode_ = getDefaultInstance().getSecCode();
      onChanged();
      return this;
    }
    /**
     * <code>required string secCode = 2;</code>
     */
    public Builder setSecCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      secCode_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object data_ = "";
    /**
     * <code>optional string data = 3;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string data = 3;</code>
     */
    public java.lang.String getData() {
      java.lang.Object ref = data_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          data_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string data = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string data = 3;</code>
     */
    public Builder setData(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      data_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string data = 3;</code>
     */
    public Builder clearData() {
      bitField0_ = (bitField0_ & ~0x00000004);
      data_ = getDefaultInstance().getData();
      onChanged();
      return this;
    }
    /**
     * <code>optional string data = 3;</code>
     */
    public Builder setDataBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      data_ = value;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.bcasekuritas.rabbitmq.proto.datafeed.OrderData)
  }

  static {
    defaultInstance = new OrderData(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:com.bcasekuritas.rabbitmq.proto.datafeed.OrderData)
}

