// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bcasdfdictionary.proto

package com.bcasekuritas.rabbitmq.proto.datafeed;

/**
 * Protobuf type {@code com.bcasekuritas.rabbitmq.proto.datafeed.TradeBookTime}
 */
public final class TradeBookTime extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.bcasekuritas.rabbitmq.proto.datafeed.TradeBookTime)
    TradeBookTimeOrBuilder {
  // Use TradeBookTime.newBuilder() to construct.
  private TradeBookTime(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private TradeBookTime(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final TradeBookTime defaultInstance;
  public static TradeBookTime getDefaultInstance() {
    return defaultInstance;
  }

  public TradeBookTime getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private TradeBookTime(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000001;
            secCode_ = bs;
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            tbtTime_ = input.readUInt64();
            break;
          }
          case 24: {
            bitField0_ |= 0x00000004;
            totalFreq_ = input.readUInt32();
            break;
          }
          case 32: {
            bitField0_ |= 0x00000008;
            buyFreq_ = input.readUInt32();
            break;
          }
          case 40: {
            bitField0_ |= 0x00000010;
            sellFreq_ = input.readUInt32();
            break;
          }
          case 48: {
            bitField0_ |= 0x00000020;
            totalLot_ = input.readUInt64();
            break;
          }
          case 56: {
            bitField0_ |= 0x00000040;
            buyLot_ = input.readUInt64();
            break;
          }
          case 64: {
            bitField0_ |= 0x00000080;
            sellLot_ = input.readUInt64();
            break;
          }
          case 73: {
            bitField0_ |= 0x00000100;
            prev_ = input.readDouble();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bcasekuritas.rabbitmq.proto.datafeed.Bcasdfdictionary.internal_static_com_bcasekuritas_rabbitmq_proto_datafeed_TradeBookTime_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bcasekuritas.rabbitmq.proto.datafeed.Bcasdfdictionary.internal_static_com_bcasekuritas_rabbitmq_proto_datafeed_TradeBookTime_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bcasekuritas.rabbitmq.proto.datafeed.TradeBookTime.class, com.bcasekuritas.rabbitmq.proto.datafeed.TradeBookTime.Builder.class);
  }

  public static com.google.protobuf.Parser<TradeBookTime> PARSER =
      new com.google.protobuf.AbstractParser<TradeBookTime>() {
    public TradeBookTime parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TradeBookTime(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<TradeBookTime> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  public static final int SECCODE_FIELD_NUMBER = 1;
  private java.lang.Object secCode_;
  /**
   * <code>required string secCode = 1;</code>
   */
  public boolean hasSecCode() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required string secCode = 1;</code>
   */
  public java.lang.String getSecCode() {
    java.lang.Object ref = secCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        secCode_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string secCode = 1;</code>
   */
  public com.google.protobuf.ByteString
      getSecCodeBytes() {
    java.lang.Object ref = secCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      secCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TBTTIME_FIELD_NUMBER = 2;
  private long tbtTime_;
  /**
   * <code>optional uint64 tbtTime = 2;</code>
   */
  public boolean hasTbtTime() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional uint64 tbtTime = 2;</code>
   */
  public long getTbtTime() {
    return tbtTime_;
  }

  public static final int TOTALFREQ_FIELD_NUMBER = 3;
  private int totalFreq_;
  /**
   * <code>optional uint32 totalFreq = 3;</code>
   */
  public boolean hasTotalFreq() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional uint32 totalFreq = 3;</code>
   */
  public int getTotalFreq() {
    return totalFreq_;
  }

  public static final int BUYFREQ_FIELD_NUMBER = 4;
  private int buyFreq_;
  /**
   * <code>optional uint32 buyFreq = 4;</code>
   */
  public boolean hasBuyFreq() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>optional uint32 buyFreq = 4;</code>
   */
  public int getBuyFreq() {
    return buyFreq_;
  }

  public static final int SELLFREQ_FIELD_NUMBER = 5;
  private int sellFreq_;
  /**
   * <code>optional uint32 sellFreq = 5;</code>
   */
  public boolean hasSellFreq() {
    return ((bitField0_ & 0x00000010) == 0x00000010);
  }
  /**
   * <code>optional uint32 sellFreq = 5;</code>
   */
  public int getSellFreq() {
    return sellFreq_;
  }

  public static final int TOTALLOT_FIELD_NUMBER = 6;
  private long totalLot_;
  /**
   * <code>optional uint64 totalLot = 6;</code>
   */
  public boolean hasTotalLot() {
    return ((bitField0_ & 0x00000020) == 0x00000020);
  }
  /**
   * <code>optional uint64 totalLot = 6;</code>
   */
  public long getTotalLot() {
    return totalLot_;
  }

  public static final int BUYLOT_FIELD_NUMBER = 7;
  private long buyLot_;
  /**
   * <code>optional uint64 buyLot = 7;</code>
   */
  public boolean hasBuyLot() {
    return ((bitField0_ & 0x00000040) == 0x00000040);
  }
  /**
   * <code>optional uint64 buyLot = 7;</code>
   */
  public long getBuyLot() {
    return buyLot_;
  }

  public static final int SELLLOT_FIELD_NUMBER = 8;
  private long sellLot_;
  /**
   * <code>optional uint64 sellLot = 8;</code>
   */
  public boolean hasSellLot() {
    return ((bitField0_ & 0x00000080) == 0x00000080);
  }
  /**
   * <code>optional uint64 sellLot = 8;</code>
   */
  public long getSellLot() {
    return sellLot_;
  }

  public static final int PREV_FIELD_NUMBER = 9;
  private double prev_;
  /**
   * <code>optional double prev = 9;</code>
   */
  public boolean hasPrev() {
    return ((bitField0_ & 0x00000100) == 0x00000100);
  }
  /**
   * <code>optional double prev = 9;</code>
   */
  public double getPrev() {
    return prev_;
  }

  private void initFields() {
    secCode_ = "";
    tbtTime_ = 0L;
    totalFreq_ = 0;
    buyFreq_ = 0;
    sellFreq_ = 0;
    totalLot_ = 0L;
    buyLot_ = 0L;
    sellLot_ = 0L;
    prev_ = 0D;
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasSecCode()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeBytes(1, getSecCodeBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeUInt64(2, tbtTime_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeUInt32(3, totalFreq_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeUInt32(4, buyFreq_);
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      output.writeUInt32(5, sellFreq_);
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      output.writeUInt64(6, totalLot_);
    }
    if (((bitField0_ & 0x00000040) == 0x00000040)) {
      output.writeUInt64(7, buyLot_);
    }
    if (((bitField0_ & 0x00000080) == 0x00000080)) {
      output.writeUInt64(8, sellLot_);
    }
    if (((bitField0_ & 0x00000100) == 0x00000100)) {
      output.writeDouble(9, prev_);
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, getSecCodeBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(2, tbtTime_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, totalFreq_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(4, buyFreq_);
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(5, sellFreq_);
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(6, totalLot_);
    }
    if (((bitField0_ & 0x00000040) == 0x00000040)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(7, buyLot_);
    }
    if (((bitField0_ & 0x00000080) == 0x00000080)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(8, sellLot_);
    }
    if (((bitField0_ & 0x00000100) == 0x00000100)) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(9, prev_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static com.bcasekuritas.rabbitmq.proto.datafeed.TradeBookTime parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bcasekuritas.rabbitmq.proto.datafeed.TradeBookTime parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bcasekuritas.rabbitmq.proto.datafeed.TradeBookTime parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bcasekuritas.rabbitmq.proto.datafeed.TradeBookTime parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bcasekuritas.rabbitmq.proto.datafeed.TradeBookTime parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.bcasekuritas.rabbitmq.proto.datafeed.TradeBookTime parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.bcasekuritas.rabbitmq.proto.datafeed.TradeBookTime parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.bcasekuritas.rabbitmq.proto.datafeed.TradeBookTime parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.bcasekuritas.rabbitmq.proto.datafeed.TradeBookTime parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.bcasekuritas.rabbitmq.proto.datafeed.TradeBookTime parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.bcasekuritas.rabbitmq.proto.datafeed.TradeBookTime prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.bcasekuritas.rabbitmq.proto.datafeed.TradeBookTime}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.bcasekuritas.rabbitmq.proto.datafeed.TradeBookTime)
      com.bcasekuritas.rabbitmq.proto.datafeed.TradeBookTimeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bcasekuritas.rabbitmq.proto.datafeed.Bcasdfdictionary.internal_static_com_bcasekuritas_rabbitmq_proto_datafeed_TradeBookTime_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bcasekuritas.rabbitmq.proto.datafeed.Bcasdfdictionary.internal_static_com_bcasekuritas_rabbitmq_proto_datafeed_TradeBookTime_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bcasekuritas.rabbitmq.proto.datafeed.TradeBookTime.class, com.bcasekuritas.rabbitmq.proto.datafeed.TradeBookTime.Builder.class);
    }

    // Construct using com.bcasekuritas.rabbitmq.proto.datafeed.TradeBookTime.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      secCode_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      tbtTime_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000002);
      totalFreq_ = 0;
      bitField0_ = (bitField0_ & ~0x00000004);
      buyFreq_ = 0;
      bitField0_ = (bitField0_ & ~0x00000008);
      sellFreq_ = 0;
      bitField0_ = (bitField0_ & ~0x00000010);
      totalLot_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000020);
      buyLot_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000040);
      sellLot_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000080);
      prev_ = 0D;
      bitField0_ = (bitField0_ & ~0x00000100);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bcasekuritas.rabbitmq.proto.datafeed.Bcasdfdictionary.internal_static_com_bcasekuritas_rabbitmq_proto_datafeed_TradeBookTime_descriptor;
    }

    public com.bcasekuritas.rabbitmq.proto.datafeed.TradeBookTime getDefaultInstanceForType() {
      return com.bcasekuritas.rabbitmq.proto.datafeed.TradeBookTime.getDefaultInstance();
    }

    public com.bcasekuritas.rabbitmq.proto.datafeed.TradeBookTime build() {
      com.bcasekuritas.rabbitmq.proto.datafeed.TradeBookTime result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.bcasekuritas.rabbitmq.proto.datafeed.TradeBookTime buildPartial() {
      com.bcasekuritas.rabbitmq.proto.datafeed.TradeBookTime result = new com.bcasekuritas.rabbitmq.proto.datafeed.TradeBookTime(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.secCode_ = secCode_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.tbtTime_ = tbtTime_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.totalFreq_ = totalFreq_;
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000008;
      }
      result.buyFreq_ = buyFreq_;
      if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
        to_bitField0_ |= 0x00000010;
      }
      result.sellFreq_ = sellFreq_;
      if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
        to_bitField0_ |= 0x00000020;
      }
      result.totalLot_ = totalLot_;
      if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
        to_bitField0_ |= 0x00000040;
      }
      result.buyLot_ = buyLot_;
      if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
        to_bitField0_ |= 0x00000080;
      }
      result.sellLot_ = sellLot_;
      if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
        to_bitField0_ |= 0x00000100;
      }
      result.prev_ = prev_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bcasekuritas.rabbitmq.proto.datafeed.TradeBookTime) {
        return mergeFrom((com.bcasekuritas.rabbitmq.proto.datafeed.TradeBookTime)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bcasekuritas.rabbitmq.proto.datafeed.TradeBookTime other) {
      if (other == com.bcasekuritas.rabbitmq.proto.datafeed.TradeBookTime.getDefaultInstance()) return this;
      if (other.hasSecCode()) {
        bitField0_ |= 0x00000001;
        secCode_ = other.secCode_;
        onChanged();
      }
      if (other.hasTbtTime()) {
        setTbtTime(other.getTbtTime());
      }
      if (other.hasTotalFreq()) {
        setTotalFreq(other.getTotalFreq());
      }
      if (other.hasBuyFreq()) {
        setBuyFreq(other.getBuyFreq());
      }
      if (other.hasSellFreq()) {
        setSellFreq(other.getSellFreq());
      }
      if (other.hasTotalLot()) {
        setTotalLot(other.getTotalLot());
      }
      if (other.hasBuyLot()) {
        setBuyLot(other.getBuyLot());
      }
      if (other.hasSellLot()) {
        setSellLot(other.getSellLot());
      }
      if (other.hasPrev()) {
        setPrev(other.getPrev());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasSecCode()) {
        
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.bcasekuritas.rabbitmq.proto.datafeed.TradeBookTime parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.bcasekuritas.rabbitmq.proto.datafeed.TradeBookTime) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object secCode_ = "";
    /**
     * <code>required string secCode = 1;</code>
     */
    public boolean hasSecCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string secCode = 1;</code>
     */
    public java.lang.String getSecCode() {
      java.lang.Object ref = secCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          secCode_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string secCode = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSecCodeBytes() {
      java.lang.Object ref = secCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        secCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string secCode = 1;</code>
     */
    public Builder setSecCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      secCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string secCode = 1;</code>
     */
    public Builder clearSecCode() {
      bitField0_ = (bitField0_ & ~0x00000001);
      secCode_ = getDefaultInstance().getSecCode();
      onChanged();
      return this;
    }
    /**
     * <code>required string secCode = 1;</code>
     */
    public Builder setSecCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      secCode_ = value;
      onChanged();
      return this;
    }

    private long tbtTime_ ;
    /**
     * <code>optional uint64 tbtTime = 2;</code>
     */
    public boolean hasTbtTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint64 tbtTime = 2;</code>
     */
    public long getTbtTime() {
      return tbtTime_;
    }
    /**
     * <code>optional uint64 tbtTime = 2;</code>
     */
    public Builder setTbtTime(long value) {
      bitField0_ |= 0x00000002;
      tbtTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint64 tbtTime = 2;</code>
     */
    public Builder clearTbtTime() {
      bitField0_ = (bitField0_ & ~0x00000002);
      tbtTime_ = 0L;
      onChanged();
      return this;
    }

    private int totalFreq_ ;
    /**
     * <code>optional uint32 totalFreq = 3;</code>
     */
    public boolean hasTotalFreq() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional uint32 totalFreq = 3;</code>
     */
    public int getTotalFreq() {
      return totalFreq_;
    }
    /**
     * <code>optional uint32 totalFreq = 3;</code>
     */
    public Builder setTotalFreq(int value) {
      bitField0_ |= 0x00000004;
      totalFreq_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint32 totalFreq = 3;</code>
     */
    public Builder clearTotalFreq() {
      bitField0_ = (bitField0_ & ~0x00000004);
      totalFreq_ = 0;
      onChanged();
      return this;
    }

    private int buyFreq_ ;
    /**
     * <code>optional uint32 buyFreq = 4;</code>
     */
    public boolean hasBuyFreq() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional uint32 buyFreq = 4;</code>
     */
    public int getBuyFreq() {
      return buyFreq_;
    }
    /**
     * <code>optional uint32 buyFreq = 4;</code>
     */
    public Builder setBuyFreq(int value) {
      bitField0_ |= 0x00000008;
      buyFreq_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint32 buyFreq = 4;</code>
     */
    public Builder clearBuyFreq() {
      bitField0_ = (bitField0_ & ~0x00000008);
      buyFreq_ = 0;
      onChanged();
      return this;
    }

    private int sellFreq_ ;
    /**
     * <code>optional uint32 sellFreq = 5;</code>
     */
    public boolean hasSellFreq() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional uint32 sellFreq = 5;</code>
     */
    public int getSellFreq() {
      return sellFreq_;
    }
    /**
     * <code>optional uint32 sellFreq = 5;</code>
     */
    public Builder setSellFreq(int value) {
      bitField0_ |= 0x00000010;
      sellFreq_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint32 sellFreq = 5;</code>
     */
    public Builder clearSellFreq() {
      bitField0_ = (bitField0_ & ~0x00000010);
      sellFreq_ = 0;
      onChanged();
      return this;
    }

    private long totalLot_ ;
    /**
     * <code>optional uint64 totalLot = 6;</code>
     */
    public boolean hasTotalLot() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional uint64 totalLot = 6;</code>
     */
    public long getTotalLot() {
      return totalLot_;
    }
    /**
     * <code>optional uint64 totalLot = 6;</code>
     */
    public Builder setTotalLot(long value) {
      bitField0_ |= 0x00000020;
      totalLot_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint64 totalLot = 6;</code>
     */
    public Builder clearTotalLot() {
      bitField0_ = (bitField0_ & ~0x00000020);
      totalLot_ = 0L;
      onChanged();
      return this;
    }

    private long buyLot_ ;
    /**
     * <code>optional uint64 buyLot = 7;</code>
     */
    public boolean hasBuyLot() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional uint64 buyLot = 7;</code>
     */
    public long getBuyLot() {
      return buyLot_;
    }
    /**
     * <code>optional uint64 buyLot = 7;</code>
     */
    public Builder setBuyLot(long value) {
      bitField0_ |= 0x00000040;
      buyLot_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint64 buyLot = 7;</code>
     */
    public Builder clearBuyLot() {
      bitField0_ = (bitField0_ & ~0x00000040);
      buyLot_ = 0L;
      onChanged();
      return this;
    }

    private long sellLot_ ;
    /**
     * <code>optional uint64 sellLot = 8;</code>
     */
    public boolean hasSellLot() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional uint64 sellLot = 8;</code>
     */
    public long getSellLot() {
      return sellLot_;
    }
    /**
     * <code>optional uint64 sellLot = 8;</code>
     */
    public Builder setSellLot(long value) {
      bitField0_ |= 0x00000080;
      sellLot_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint64 sellLot = 8;</code>
     */
    public Builder clearSellLot() {
      bitField0_ = (bitField0_ & ~0x00000080);
      sellLot_ = 0L;
      onChanged();
      return this;
    }

    private double prev_ ;
    /**
     * <code>optional double prev = 9;</code>
     */
    public boolean hasPrev() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional double prev = 9;</code>
     */
    public double getPrev() {
      return prev_;
    }
    /**
     * <code>optional double prev = 9;</code>
     */
    public Builder setPrev(double value) {
      bitField0_ |= 0x00000100;
      prev_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional double prev = 9;</code>
     */
    public Builder clearPrev() {
      bitField0_ = (bitField0_ & ~0x00000100);
      prev_ = 0D;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.bcasekuritas.rabbitmq.proto.datafeed.TradeBookTime)
  }

  static {
    defaultInstance = new TradeBookTime(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:com.bcasekuritas.rabbitmq.proto.datafeed.TradeBookTime)
}

