// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bcasdfdictionary.proto

package com.bcasekuritas.rabbitmq.proto.datafeed;

public interface TradingSummaryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.bcasekuritas.rabbitmq.proto.datafeed.TradingSummary)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .com.bcasekuritas.rabbitmq.proto.datafeed.TSSecurityType ordiTSSecType = 1;</code>
   *
   * <pre>
   *trading summary
   * </pre>
   */
  boolean hasOrdiTSSecType();
  /**
   * <code>optional .com.bcasekuritas.rabbitmq.proto.datafeed.TSSecurityType ordiTSSecType = 1;</code>
   *
   * <pre>
   *trading summary
   * </pre>
   */
  com.bcasekuritas.rabbitmq.proto.datafeed.TSSecurityType getOrdiTSSecType();
  /**
   * <code>optional .com.bcasekuritas.rabbitmq.proto.datafeed.TSSecurityType ordiTSSecType = 1;</code>
   *
   * <pre>
   *trading summary
   * </pre>
   */
  com.bcasekuritas.rabbitmq.proto.datafeed.TSSecurityTypeOrBuilder getOrdiTSSecTypeOrBuilder();

  /**
   * <code>optional .com.bcasekuritas.rabbitmq.proto.datafeed.TSSecurityType rghiTSSecType = 2;</code>
   */
  boolean hasRghiTSSecType();
  /**
   * <code>optional .com.bcasekuritas.rabbitmq.proto.datafeed.TSSecurityType rghiTSSecType = 2;</code>
   */
  com.bcasekuritas.rabbitmq.proto.datafeed.TSSecurityType getRghiTSSecType();
  /**
   * <code>optional .com.bcasekuritas.rabbitmq.proto.datafeed.TSSecurityType rghiTSSecType = 2;</code>
   */
  com.bcasekuritas.rabbitmq.proto.datafeed.TSSecurityTypeOrBuilder getRghiTSSecTypeOrBuilder();

  /**
   * <code>optional .com.bcasekuritas.rabbitmq.proto.datafeed.TSSecurityType wariTSSecType = 3;</code>
   */
  boolean hasWariTSSecType();
  /**
   * <code>optional .com.bcasekuritas.rabbitmq.proto.datafeed.TSSecurityType wariTSSecType = 3;</code>
   */
  com.bcasekuritas.rabbitmq.proto.datafeed.TSSecurityType getWariTSSecType();
  /**
   * <code>optional .com.bcasekuritas.rabbitmq.proto.datafeed.TSSecurityType wariTSSecType = 3;</code>
   */
  com.bcasekuritas.rabbitmq.proto.datafeed.TSSecurityTypeOrBuilder getWariTSSecTypeOrBuilder();

  /**
   * <code>optional .com.bcasekuritas.rabbitmq.proto.datafeed.TSSecurityType mutiTSSecType = 4;</code>
   */
  boolean hasMutiTSSecType();
  /**
   * <code>optional .com.bcasekuritas.rabbitmq.proto.datafeed.TSSecurityType mutiTSSecType = 4;</code>
   */
  com.bcasekuritas.rabbitmq.proto.datafeed.TSSecurityType getMutiTSSecType();
  /**
   * <code>optional .com.bcasekuritas.rabbitmq.proto.datafeed.TSSecurityType mutiTSSecType = 4;</code>
   */
  com.bcasekuritas.rabbitmq.proto.datafeed.TSSecurityTypeOrBuilder getMutiTSSecTypeOrBuilder();

  /**
   * <code>optional .com.bcasekuritas.rabbitmq.proto.datafeed.TSData grandTotalTSData = 5;</code>
   */
  boolean hasGrandTotalTSData();
  /**
   * <code>optional .com.bcasekuritas.rabbitmq.proto.datafeed.TSData grandTotalTSData = 5;</code>
   */
  com.bcasekuritas.rabbitmq.proto.datafeed.TSData getGrandTotalTSData();
  /**
   * <code>optional .com.bcasekuritas.rabbitmq.proto.datafeed.TSData grandTotalTSData = 5;</code>
   */
  com.bcasekuritas.rabbitmq.proto.datafeed.TSDataOrBuilder getGrandTotalTSDataOrBuilder();

  /**
   * <code>optional .com.bcasekuritas.rabbitmq.proto.datafeed.FDBuySell buyFD = 6;</code>
   *
   * <pre>
   *buy/sell foreign &lt;&gt; domestic
   * </pre>
   */
  boolean hasBuyFD();
  /**
   * <code>optional .com.bcasekuritas.rabbitmq.proto.datafeed.FDBuySell buyFD = 6;</code>
   *
   * <pre>
   *buy/sell foreign &lt;&gt; domestic
   * </pre>
   */
  com.bcasekuritas.rabbitmq.proto.datafeed.FDBuySell getBuyFD();
  /**
   * <code>optional .com.bcasekuritas.rabbitmq.proto.datafeed.FDBuySell buyFD = 6;</code>
   *
   * <pre>
   *buy/sell foreign &lt;&gt; domestic
   * </pre>
   */
  com.bcasekuritas.rabbitmq.proto.datafeed.FDBuySellOrBuilder getBuyFDOrBuilder();

  /**
   * <code>optional .com.bcasekuritas.rabbitmq.proto.datafeed.FDBuySell sellFD = 7;</code>
   */
  boolean hasSellFD();
  /**
   * <code>optional .com.bcasekuritas.rabbitmq.proto.datafeed.FDBuySell sellFD = 7;</code>
   */
  com.bcasekuritas.rabbitmq.proto.datafeed.FDBuySell getSellFD();
  /**
   * <code>optional .com.bcasekuritas.rabbitmq.proto.datafeed.FDBuySell sellFD = 7;</code>
   */
  com.bcasekuritas.rabbitmq.proto.datafeed.FDBuySellOrBuilder getSellFDOrBuilder();

  /**
   * <code>optional sint64 netF = 8;</code>
   */
  boolean hasNetF();
  /**
   * <code>optional sint64 netF = 8;</code>
   */
  long getNetF();

  /**
   * <code>optional sint64 netOwn = 9;</code>
   */
  boolean hasNetOwn();
  /**
   * <code>optional sint64 netOwn = 9;</code>
   */
  long getNetOwn();
}
